#######
# Compiled from escapemap/functions/ep/test2.mcscript
# to .//data/escapemap/functions/ep/test2/click_10.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=ep_ia_test2,tag=10] run data remove entity @s interaction
scoreboard players set P ep_test2_progress 11
execute if score P ep_test2_progress matches 11 run function escapemap:ep/test2/complete
