#######
# Compiled from escapemap/functions/ep/test2.mcscript
# to .//data/escapemap/functions/ep/test2/particle_10.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -2.5 275.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -2.5 275.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -3.0 275.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.0 275.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 275.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 276.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -2.5 276.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -2.5 276.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -3.0 276.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.0 276.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 276.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 277.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -2.5 277.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -2.5 277.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -3.0 277.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.0 277.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 277.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -2.5 279.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -2.5 279.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -3.0 279.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.0 279.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 280.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -2.5 280.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -2.5 280.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -3.0 280.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.0 280.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 280.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 281.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -2.5 281.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -2.5 281.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -3.0 281.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.0 281.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 281.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 282.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -2.5 282.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -2.5 282.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -3.0 282.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.0 282.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 282.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -2.5 283.0 0.5 0.5 0 0 1