#######
# Compiled from escapemap/functions/ep/test2.mcscript
# to .//data/escapemap/functions/ep/test2/particle_1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:dust{color:[1,1,1],scale:1} -170.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -2.5 279.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -161.0 -2.5 278.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -161.5 -3.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -161.5 -2.0 278.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -161.5 -2.5 278.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -161.5 -2.5 279.0 0.5 0.5 0 0 1
