#######
# Compiled from escapemap/functions/ep/test2.mcscript
# to .//data/escapemap/functions/ep/test2/particle_7.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:dust{color:[1,1,1],scale:1} -167.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.5 -3.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.5 -2.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.5 -2.5 284.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -166.5 -2.5 285.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.5 -3.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.5 -2.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.5 -2.5 284.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -167.5 -2.5 285.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.5 -3.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.5 -2.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.5 -2.5 284.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -168.5 -2.5 285.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -170.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.5 -3.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.5 -2.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.5 -2.5 284.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -169.5 -2.5 285.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -171.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -170.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -170.5 -3.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -170.5 -2.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -170.5 -2.5 284.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -170.5 -2.5 285.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -172.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -171.0 -2.5 284.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -171.5 -3.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -171.5 -2.0 284.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -171.5 -2.5 284.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -171.5 -2.5 285.0 0.5 0.5 0 0 1
