#######
# Compiled from castle/layer2/elevators/controller.mcscript
# to .//data/escapemap/functions/puzzles/castle/layer2/elevators/controller/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/castle/layer2/elevators/elevator/load
