#######
# Compiled from castle/layer2/elevators/controller.mcscript
# to .//data/escapemap/functions/puzzles/castle/layer2/elevators/controller/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set C crafters_completed 0
fill -164 -45 -42 -162 -45 -44 air
function escapemap:puzzles/castle/layer2/elevators/elevator/reset
