#######
# Compiled from puzzles/desert/depths/mini.mcscript
# to .//data/escapemap/functions/puzzles/desert/depths/pp4/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P desert_pp4 matches 0 run function escapemap:puzzles/complete
execute if score P desert_pp4 matches 0 run setblock -177 -49 44 minecraft:waxed_oxidized_copper_bulb[lit=true]
execute if score P desert_pp4 matches 0 run schedule function escapemap:puzzles/desert/depths/pp4/door 5s

scoreboard players set P desert_pp4 1
function escapemap:puzzles/desert/ocd/check
