#######
# Compiled from functions/puzzles/desert/lights_out.mcscript
# to .//data/escapemap/functions/puzzles/desert/ocd/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P desert_ocd matches 0 run setblock -187 -49 29 waxed_copper_bulb[lit=true]
execute if score P desert_ocd matches 0 run function escapemap:puzzles/secret_complete {p:"-187 -50 31"}

scoreboard players set P desert_ocd 1
