#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_013.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248693f,3.454881f,-0.018699f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.536124f,-0.463872f,0.497326f,0.500060f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.621733f,3.480953f,-0.046748f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.536124f,-0.463872f,0.497326f,0.500060f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
