#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_041.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.243318f,3.491922f,-0.018295f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.572055f,-0.425339f,0.530657f,0.458521f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.608294f,3.573556f,-0.045738f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.572055f,-0.425339f,0.530657f,0.458521f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
