#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_044.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.242415f,3.495833f,-0.018227f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.575718f,-0.421065f,0.534055f,0.453914f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.606037f,3.583333f,-0.045568f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.575718f,-0.421065f,0.534055f,0.453914f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
