#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_059.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.236969f,3.515141f,-0.017818f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.593471f,-0.399294f,0.550523f,0.430444f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.592423f,3.631604f,-0.044544f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.593471f,-0.399294f,0.550523f,0.430444f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
