#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_005.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249207f,3.444190f,-0.018738f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.525296f,-0.474413f,0.487282f,0.511423f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.623018f,3.454224f,-0.046845f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.525296f,-0.474413f,0.487282f,0.511423f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
