#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_001.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249293f,3.438838f,-0.018744f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.519791f,-0.479601f,0.482175f,0.517017f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.623232f,3.440845f,-0.046861f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.519791f,-0.479601f,0.482175f,0.517017f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
