#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_027.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.246698f,3.473503f,-0.018549f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.554479f,-0.444918f,0.514353f,0.479628f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.616744f,3.527507f,-0.046373f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.554479f,-0.444918f,0.514353f,0.479628f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
