#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_011.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248864f,3.452210f,-0.018712f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.533440f,-0.466527f,0.494836f,0.502923f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.622161f,3.474276f,-0.046781f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.533440f,-0.466527f,0.494836f,0.502923f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
