#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_032.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.245649f,3.480110f,-0.018470f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.560847f,-0.437996f,0.520260f,0.472165f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.614122f,3.544024f,-0.046176f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.560847f,-0.437996f,0.520260f,0.472165f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
