#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_047.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.241450f,3.499729f,-0.018155f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.579344f,-0.416764f,0.537418f,0.449277f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.603624f,3.593072f,-0.045387f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.579344f,-0.416764f,0.537418f,0.449277f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
