#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_025.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247068f,3.470852f,-0.018577f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.551904f,-0.447665f,0.511964f,0.482588f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.617670f,3.520881f,-0.046443f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.551904f,-0.447665f,0.511964f,0.482588f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
