#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_007.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249121f,3.446864f,-0.018732f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.528026f,-0.471798f,0.489814f,0.508604f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.622803f,3.460911f,-0.046829f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.528026f,-0.471798f,0.489814f,0.508604f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
