#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_003.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249264f,3.441514f,-0.018742f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.522551f,-0.477014f,0.484735f,0.514227f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.623160f,3.447535f,-0.046856f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.522551f,-0.477014f,0.484735f,0.514227f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
