#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_073.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.230508f,3.532714f,-0.017332f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.609178f,-0.378392f,0.565093f,0.407912f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.576270f,3.675535f,-0.043330f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.609178f,-0.378392f,0.565093f,0.407912f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
