#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_038.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.244158f,3.487997f,-0.018358f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.568356f,-0.429586f,0.527225f,0.463099f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.610394f,3.563744f,-0.045896f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.568356f,-0.429586f,0.527225f,0.463099f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
