#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_050.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.240422f,3.503609f,-0.018077f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.582932f,-0.412436f,0.540747f,0.444612f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.601056f,3.602771f,-0.045194f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.582932f,-0.412436f,0.540747f,0.444612f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
