#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_020.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247869f,3.464211f,-0.018637f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.545397f,-0.454475f,0.505928f,0.489930f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.619673f,3.504277f,-0.046593f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.545397f,-0.454475f,0.505928f,0.489930f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
