#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_067.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.233438f,3.525243f,-0.017552f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.602550f,-0.387417f,0.558945f,0.417640f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.583594f,3.656856f,-0.043881f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.602550f,-0.387417f,0.558945f,0.417640f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
