#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_028.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.246502f,3.474826f,-0.018535f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.555760f,-0.443540f,0.515541f,0.478142f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.616255f,3.530816f,-0.046336f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.555760f,-0.443540f,0.515541f,0.478142f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
