#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_061.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.236127f,3.517681f,-0.017754f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.595766f,-0.396341f,0.552652f,0.427261f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.590317f,3.637952f,-0.044386f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.595766f,-0.396341f,0.552652f,0.427261f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
