#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_069.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.232488f,3.527743f,-0.017481f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.604776f,-0.384419f,0.561010f,0.414409f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.581219f,3.663108f,-0.043702f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.604776f,-0.384419f,0.561010f,0.414409f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
