#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_012.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248782f,3.453546f,-0.018706f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.534784f,-0.465201f,0.496083f,0.501493f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.621956f,3.477615f,-0.046765f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.534784f,-0.465201f,0.496083f,0.501493f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
