#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_019.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248008f,3.462880f,-0.018648f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.544084f,-0.455827f,0.504710f,0.491388f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.620021f,3.500950f,-0.046620f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.544084f,-0.455827f,0.504710f,0.491388f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
