#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_004.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249239f,3.442852f,-0.018740f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.523925f,-0.475715f,0.486010f,0.512827f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.623098f,3.450880f,-0.046851f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.523925f,-0.475715f,0.486010f,0.512827f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
