#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_052.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.239703f,3.506186f,-0.018023f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.585304f,-0.409536f,0.542947f,0.441485f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.599257f,3.609214f,-0.045058f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.585304f,-0.409536f,0.542947f,0.441485f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
