#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_07_pitch/frame_024.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247242f,3.469526f,-0.018590f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.550610f,-0.449033f,0.510764f,0.484064f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.618106f,3.517565f,-0.046476f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.550610f,-0.449033f,0.510764f,0.484064f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
