#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_01_flaps/frame_030.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,1.158963f,0.576260f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.318339f,0.000000f,0.000000f,0.947977f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,1.158963f,-0.576260f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.318339f,0.000000f,0.000000f,0.947977f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
