#######
# Compiled from escapemap/functions/puzzles/village_yard.mcscript
# to .//data/escapemap/functions/puzzles/village_yard/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -32 -37 34 minecraft:andesite_wall
function escapemap:puzzles/complete
