#######
# Compiled from escapemap/functions/puzzles/village_yard.mcscript
# to .//data/escapemap/functions/puzzles/village_yard/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -32 -37 34 minecraft:andesite
setblock -33 -37 34 minecraft:waxed_oxidized_copper_bulb[powered=false]
fill -30 -37 39 -27 -37 34 air
setblock -31 -37 34 air
setblock -30 -37 32 air
setblock -30 -37 33 air
setblock -29 -37 33 air
setblock -28 -37 33 air
setblock -29 -39 31 minecraft:stone_button[face=ceiling,powered=true]