#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_01_flaps/frame_052.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:1,transformation:{translation:[0.000000f,3.431370f,-1.834105f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.956940f,0.000000f,0.000000f,0.290285f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:1,transformation:{translation:[0.000000f,3.431370f,1.834105f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.956940f,0.000000f,0.000000f,0.290285f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
