#######
# Compiled from functions/puzzles/desert/elevator.mcscript
# to .//data/escapemap/functions/puzzles/desert/elevator/despawn_entities.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=escapemap_desert_elevator] at @s run tp @s 0 -64 0
kill @e[type=minecraft:shulker,tag=escapemap_desert_elevator]
kill @e[type=minecraft:block_display,tag=escapemap_desert_elevator_display]
