#######
# Compiled from functions/puzzles/desert/elevator.mcscript
# to .//data/escapemap/functions/puzzles/desert/elevator/force_attach_face.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:shulker,tag=escapemap_desert_elevator] run data merge entity @s {AttachFace:0b}
