#######
# Compiled from functions/puzzles/desert/elevator.mcscript
# to .//data/escapemap/functions/puzzles/desert/elevator/place_station_1_blocks.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -169 -38 31 minecraft:polished_andesite
setblock -169 -38 30 minecraft:polished_andesite
setblock -169 -38 29 minecraft:polished_andesite
setblock -169 -38 32 minecraft:polished_andesite
setblock -169 -38 33 minecraft:polished_andesite
setblock -168 -38 31 minecraft:polished_andesite
setblock -168 -38 30 minecraft:polished_andesite
setblock -168 -38 29 minecraft:polished_andesite
setblock -168 -38 32 minecraft:polished_andesite
setblock -168 -38 33 minecraft:polished_andesite
setblock -170 -38 31 minecraft:polished_andesite
setblock -170 -38 30 minecraft:polished_andesite
setblock -170 -38 29 minecraft:polished_andesite
setblock -170 -38 32 minecraft:polished_andesite
setblock -170 -38 33 minecraft:polished_andesite
setblock -171 -38 30 minecraft:polished_andesite
setblock -171 -38 31 minecraft:polished_andesite
setblock -171 -38 32 minecraft:polished_andesite
setblock -167 -38 30 minecraft:polished_andesite
setblock -167 -38 31 minecraft:polished_andesite
setblock -167 -38 32 minecraft:polished_andesite
setblock -168 -37 32 minecraft:deepslate_tile_wall[north=tall,west=tall]
setblock -168 -36 32 minecraft:deepslate_tile_wall[north=tall,west=tall]
setblock -168 -35 32 minecraft:deepslate_tile_wall[north=low,west=low]
setblock -170 -37 32 minecraft:deepslate_tile_wall[north=tall,east=tall]
setblock -170 -36 32 minecraft:deepslate_tile_wall[north=tall,east=tall]
setblock -170 -35 32 minecraft:deepslate_tile_wall[north=low,east=low]
setblock -170 -37 30 minecraft:deepslate_tile_wall[south=tall,east=tall]
setblock -170 -36 30 minecraft:deepslate_tile_wall[south=tall,east=tall]
setblock -170 -35 30 minecraft:deepslate_tile_wall[south=low,east=low]
setblock -168 -37 30 minecraft:deepslate_tile_wall[south=tall,west=tall]
setblock -168 -36 30 minecraft:deepslate_tile_wall[south=tall,west=tall]
setblock -168 -35 30 minecraft:deepslate_tile_wall[south=low,west=low]
setblock -169 -37 32 minecraft:iron_bars[east=true,west=true]
setblock -169 -36 32 minecraft:iron_bars[east=true,west=true]
setblock -169 -35 32 minecraft:deepslate_tile_wall[east=low,west=low]
setblock -169 -37 30 minecraft:iron_bars[east=true,west=true]
setblock -169 -36 30 minecraft:iron_bars[east=true,west=true]
setblock -169 -35 30 minecraft:deepslate_tile_wall[east=low,west=low]
setblock -168 -37 31 minecraft:iron_bars[north=true,south=true]
setblock -168 -36 31 minecraft:iron_bars[north=true,south=true]
setblock -168 -35 31 minecraft:deepslate_tile_wall[north=low,south=low]
setblock -170 -37 31 minecraft:iron_bars[north=true,south=true]
setblock -170 -36 31 minecraft:iron_bars[north=true,south=true]
setblock -170 -35 31 minecraft:deepslate_tile_wall[north=low,south=low]
