#######
# Compiled from functions/puzzles/red_candle/cave.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/cave/warped/expireblock.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -56 -45 65 warped_hyphae
setblock -65 -43 66 warped_hyphae
