#######
# Compiled from puzzles/castle/secrets/wall_top.mcscript
# to .//data/escapemap/functions/puzzles/castle/secrets/walltop/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P secrets_castle_walltop_complete matches 0 run setblock -185 -32 -34 minecraft:waxed_copper_bulb[lit=true,powered=false]
execute if score P secrets_castle_walltop_complete matches 0 run function escapemap:puzzles/secret_complete {p:"-185 -31 -34"}
execute if score P secrets_castle_walltop_complete matches 0 run scoreboard players set P secrets_castle_walltop_complete 1

