#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/test.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/test/click_0.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_test,tag=0] run data remove entity @s interaction
kill @e[tag=zzz_ia_test,tag=1]
kill @e[tag=zzz_ia_test,tag=2]
kill @e[tag=zzz_ia_test,tag=3]
kill @e[tag=zzz_ia_test,tag=4]
kill @e[tag=zzz_ia_test,tag=5]
summon interaction -165 -6 276 {Tags:["zzz_ia_test", "1"],height:1.1f,width:1.1f}
scoreboard players set P zzz_test_progress 1
execute if score P zzz_test_progress matches 6 run function escapemap:zzz/test/complete
