#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/test.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/test/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say complete
function escapemap:zzz/test/kill
