#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/test.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/test/particle_5.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:dust{color:[1,1,1],scale:1} -163.0 -5.5 272.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.0 -5.5 272.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -6.0 272.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -5.0 272.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -5.5 272.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -5.5 273.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.0 -5.5 273.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.0 -5.5 273.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -6.0 273.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -5.0 273.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -5.5 273.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -5.5 274.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.0 -5.5 274.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.0 -5.5 274.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -6.0 274.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -5.0 274.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -5.5 274.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -162.5 -5.5 275.0 0.5 0.5 0 0 1