#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/test.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/test/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:zzz/test/kill
function escapemap:zzz/test/summon0
scoreboard players set P zzz_test_progress 0
