#######
# Compiled from functions/puzzles/desert/elevator_controller.mcscript
# to .//data/escapemap/functions/puzzles/desert/elevator_controller/start.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/desert/elevator/go_to_top
fill -167 -36 29 -171 -36 33 air replace barrier
fill -169 -48 31 -169 -46 31 air
tp @p -169 -49 31
