#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_01_flaps/frame_117.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,3.440843f,-1.783087f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.953158f,0.000000f,0.000000f,0.302474f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,3.440843f,1.783087f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.953158f,0.000000f,0.000000f,0.302474f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
