#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_01_flaps/frame_059.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.392295f,0.357264f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.594910f,0.000000f,0.000000f,0.803792f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.392295f,-0.357264f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.594910f,0.000000f,0.000000f,0.803792f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
