#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_020.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.043412f,3.458958f,-0.245265f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.734472f,-0.064258f,0.058882f,0.673019f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.108530f,3.491145f,-0.613163f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.734472f,-0.064258f,0.058882f,0.673019f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
