#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_072.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.146946f,3.500000f,-0.192355f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769421f,-0.250000f,0.181636f,0.559017f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.367366f,3.593750f,-0.480888f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769421f,-0.250000f,0.181636f,0.559017f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
