#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_012.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.026132f,3.450512f,-0.248290f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.724380f,-0.037963f,0.036026f,0.687411f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.065330f,3.470031f,-0.620724f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.724380f,-0.037963f,0.036026f,0.687411f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
