#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_022.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.047702f,3.461021f,-0.244277f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.736810f,-0.070947f,0.064444f,0.669271f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.119256f,3.496303f,-0.610692f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.736810f,-0.070947f,0.064444f,0.669271f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
