#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_078.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.157330f,3.502354f,-0.183143f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769800f,-0.272601f,0.192655f,0.544041f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.393325f,3.599635f,-0.457856f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769800f,-0.272601f,0.192655f,0.544041f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
