#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_013.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.028301f,3.451582f,-0.247993f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.725705f,-0.041209f,0.038935f,0.685666f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.070752f,3.472705f,-0.619984f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.725705f,-0.041209f,0.038935f,0.685666f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
