#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_026.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.056238f,3.465075f,-0.242027f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.741262f,-0.084456f,0.075380f,0.661601f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.140594f,3.506439f,-0.605067f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.741262f,-0.084456f,0.075380f,0.661601f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
