#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_039.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.083452f,3.477409f,-0.232257f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.753596f,-0.129491f,0.109139f,0.635149f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.208629f,3.537272f,-0.580641f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.753596f,-0.129491f,0.109139f,0.635149f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
