#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_030.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.064705f,3.469020f,-0.239416f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.745408f,-0.098135f,0.086062f,0.653705f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.161762f,3.516299f,-0.598539f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.745408f,-0.098135f,0.086062f,0.653705f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
