#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_063.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.130625f,3.495360f,-0.205157f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.767385f,-0.216425f,0.163829f,0.580896f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.326562f,3.582151f,-0.512892f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.767385f,-0.216425f,0.163829f,0.580896f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
