#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_077.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.155629f,3.502005f,-0.184713f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769792f,-0.268823f,0.190866f,0.546557f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.389072f,3.598762f,-0.461782f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769792f,-0.268823f,0.190866f,0.546557f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
