#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_018.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.039109f,3.456873f,-0.246161f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.732059f,-0.057614f,0.053258f,0.676708f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.097772f,3.485933f,-0.615402f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.732059f,-0.057614f,0.053258f,0.676708f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
