#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_061.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.126885f,3.494159f,-0.207822f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.766697f,-0.209026f,0.159668f,0.585654f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.317211f,3.579147f,-0.519556f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.766697f,-0.209026f,0.159668f,0.585654f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
