#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_024.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.051978f,3.463061f,-0.243197f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.739074f,-0.077680f,0.069943f,0.665465f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.129945f,3.501403f,-0.607993f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.739074f,-0.077680f,0.069943f,0.665465f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
