#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_059.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.123106f,3.492899f,-0.210418f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.765923f,-0.201651f,0.155432f,0.590373f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.307765f,3.575996f,-0.526046f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.765923f,-0.201651f,0.155432f,0.590373f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
