#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_066.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.136160f,3.497049f,-0.201033f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.768258f,-0.227568f,0.169933f,0.573685f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.340399f,3.586372f,-0.502584f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.768258f,-0.227568f,0.169933f,0.573685f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
