#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_068.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.139798f,3.498097f,-0.198203f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.768732f,-0.235025f,0.173909f,0.568832f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.349496f,3.588992f,-0.495508f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.768732f,-0.235025f,0.173909f,0.568832f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
