#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_045.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.095671f,3.482560f,-0.226532f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.758157f,-0.150807f,0.123764f,0.622204f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.239177f,3.550150f,-0.566330f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.758157f,-0.150807f,0.123764f,0.622204f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
