#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_014.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.030467f,3.452648f,-0.247674f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.727012f,-0.044466f,0.041829f,0.683905f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.076168f,3.475371f,-0.619184f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.727012f,-0.044466f,0.041829f,0.683905f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
