#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_046.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.097683f,3.483380f,-0.225506f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.758846f,-0.154389f,0.126141f,0.620004f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.244207f,3.552199f,-0.563766f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.758846f,-0.154389f,0.126141f,0.620004f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
