#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_075.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.152190f,3.501254f,-0.187813f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769709f,-0.261281f,0.187231f,0.551566f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.380476f,3.596884f,-0.469531f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769709f,-0.261281f,0.187231f,0.551566f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
