#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_final_aim/frame_080.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.160697f,3.503001f,-0.179962f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769751f,-0.280166f,0.196175f,0.538986f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.401742f,3.601252f,-0.449904f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.769751f,-0.280166f,0.196175f,0.538986f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
