#######
# Compiled from puzzles/desert/lights/tutorial.mcscript
# to .//data/escapemap/functions/puzzles/desert/lights/pp1/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P desert_pp1 matches 0 run function escapemap:puzzles/complete
execute if score P desert_pp1 matches 0 run setblock -164 -42 51 minecraft:waxed_oxidized_copper_bulb[lit=true]
execute if score P desert_pp1 matches 0 run schedule function escapemap:puzzles/desert/lights/pp1/door 5s

scoreboard players set P desert_pp1 1
