#######
# Compiled from puzzles/desert/lights/tutorial.mcscript
# to .//data/escapemap/functions/puzzles/desert/lights/pp1/door_start.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:block_display,tag=door_stair_pp1] run data merge entity @s {start_interpolation:0,transformation:{translation:[-0.5f,-2f,-0.5f],left_rotation:[0f,0f,0f,1f],scale:[1f,1f,1f],right_rotation:[0f,0f,0f,1f]}}
schedule function escapemap:puzzles/desert/lights/pp1/door_clear 200t replace
