#######
# Compiled from functions/puzzles/cyan_candle/part1.mcscript
# to .//data/escapemap/functions/puzzles/cyan_candle/part1/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -53 -37 49 minecraft:chest[facing=east] destroy
setblock -108 -38 40 redstone_torch
function escapemap:puzzles/complete
