#######
# Compiled from data/escapemap/functions/drop.mcscript
# to .//data/escapemap/functions/drop/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=item] unless data entity @s {Item:{components:{"minecraft:custom_data":{"puzzle":{"id":"ground"}}}}} at @s run tp @s @p