#######
# Compiled from functions/puzzles/desert/little_secret.mcscript
# to .//data/escapemap/functions/puzzles/desert/ls1/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P desert_ls1 matches 0 run function escapemap:puzzles/secret_complete {p:'-156 -51 28'}
execute if score P desert_ls1 matches 0 run setblock -160 -49 30 minecraft:waxed_copper_bulb[lit=true]

scoreboard players set P desert_ls1 1