#######
# Compiled from functions/puzzles/desert/little_secret.mcscript
# to .//data/escapemap/functions/puzzles/desert/ls1/toggle3.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data modify storage escapemap:tmp isStone3 set value 0b
execute if block ~ ~2 ~-2 stone_pressure_plate positioned ~ ~2 ~-2 unless entity @e[tag=ls1_fake3,distance=..1] run data modify storage escapemap:tmp isStone3 set value 1b
execute if block ~ ~2 ~-2 stone_pressure_plate if data storage escapemap:tmp {isStone3:1b} positioned ~ ~2 ~-2 run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["ls1_fake3", "ls1_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if block ~ ~2 ~-2 stone_pressure_plate if data storage escapemap:tmp {isStone3:0b} positioned ~ ~2 ~-2 as @e[tag=ls1_fake3,distance=..1] run kill @s
data modify storage escapemap:tmp isStone3 set value 0b
execute if block ~ ~2 ~2 stone_pressure_plate positioned ~ ~2 ~2 unless entity @e[tag=ls1_fake3,distance=..1] run data modify storage escapemap:tmp isStone3 set value 1b
execute if block ~ ~2 ~2 stone_pressure_plate if data storage escapemap:tmp {isStone3:1b} positioned ~ ~2 ~2 run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["ls1_fake3", "ls1_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if block ~ ~2 ~2 stone_pressure_plate if data storage escapemap:tmp {isStone3:0b} positioned ~ ~2 ~2 as @e[tag=ls1_fake3,distance=..1] run kill @s
data modify storage escapemap:tmp isStone3 set value 0b
execute if block ~-2 ~2 ~ stone_pressure_plate positioned ~-2 ~2 ~ unless entity @e[tag=ls1_fake3,distance=..1] run data modify storage escapemap:tmp isStone3 set value 1b
execute if block ~-2 ~2 ~ stone_pressure_plate if data storage escapemap:tmp {isStone3:1b} positioned ~-2 ~2 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["ls1_fake3", "ls1_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if block ~-2 ~2 ~ stone_pressure_plate if data storage escapemap:tmp {isStone3:0b} positioned ~-2 ~2 ~ as @e[tag=ls1_fake3,distance=..1] run kill @s
data modify storage escapemap:tmp isStone3 set value 0b
execute if block ~2 ~2 ~ stone_pressure_plate positioned ~2 ~2 ~ unless entity @e[tag=ls1_fake3,distance=..1] run data modify storage escapemap:tmp isStone3 set value 1b
execute if block ~2 ~2 ~ stone_pressure_plate if data storage escapemap:tmp {isStone3:1b} positioned ~2 ~2 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["ls1_fake3", "ls1_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if block ~2 ~2 ~ stone_pressure_plate if data storage escapemap:tmp {isStone3:0b} positioned ~2 ~2 ~ as @e[tag=ls1_fake3,distance=..1] run kill @s
data modify storage escapemap:tmp isStone3 set value 0b
execute positioned ~ ~2 ~ unless entity @e[tag=ls1_fake3,distance=..1] run data modify storage escapemap:tmp isStone3 set value 1b
execute if data storage escapemap:tmp {isStone3:1b} positioned ~ ~2 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["ls1_fake3", "ls1_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if data storage escapemap:tmp {isStone3:0b} positioned ~ ~2 ~ as @e[tag=ls1_fake3,distance=..1] run kill @s
function escapemap:puzzles/desert/ls1/check
