#######
# Compiled from escapemap/functions/ep/castle_tower.mcscript
# to .//data/escapemap/functions/ep/castle_tower/click_5.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=ep_ia_castle_tower,tag=5] run data remove entity @s interaction
scoreboard players set P ep_castle_tower_progress 6
execute if score P ep_castle_tower_progress matches 6 run function escapemap:ep/castle_tower/complete
