#######
# Compiled from escapemap/functions/ep/castle_tower.mcscript
# to .//data/escapemap/functions/ep/castle_tower/click_1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=ep_ia_castle_tower,tag=1] run data remove entity @s interaction
kill @e[tag=ep_ia_castle_tower,tag=2]
kill @e[tag=ep_ia_castle_tower,tag=3]
kill @e[tag=ep_ia_castle_tower,tag=4]
kill @e[tag=ep_ia_castle_tower,tag=5]
summon interaction -160 -18 -53 {Tags:["ep_ia_castle_tower", "2"],height:1.1f,width:1.1f}
scoreboard players set P ep_castle_tower_progress 2
execute if score P ep_castle_tower_progress matches 6 run function escapemap:ep/castle_tower/complete
