#######
# Compiled from escapemap/functions/ep/castle_tower.mcscript
# to .//data/escapemap/functions/ep/castle_tower/particle_5.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:dust{color:[1,1,1],scale:1} -166.0 -18.1 -49.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.0 -18.1 -49.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.5 -17.6 -49.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.5 -18.1 -50.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.5 -18.1 -49.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -165.0 -18.1 -49.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.0 -18.1 -49.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.5 -17.6 -49.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.5 -18.1 -50.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.5 -18.1 -49.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -164.0 -18.1 -49.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.0 -18.1 -49.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.5 -17.6 -49.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.5 -18.1 -50.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -163.5 -18.1 -49.0 0.5 0.5 0 0 1