#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/desert_bushes.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/desert_bushes/click_3.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_desert_bushes,tag=3] run data remove entity @s interaction
kill @e[tag=zzz_ia_desert_bushes,tag=4]
kill @e[tag=zzz_ia_desert_bushes,tag=5]
summon interaction -175 -37 10 {Tags:["zzz_ia_desert_bushes", "4"],height:1.1f,width:1.1f}
scoreboard players set P zzz_desert_bushes_progress 4
execute if score P zzz_desert_bushes_progress matches 6 run function escapemap:zzz/desert_bushes/complete
