#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/desert_bushes.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/desert_bushes/click_4.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_desert_bushes,tag=4] run data remove entity @s interaction
kill @e[tag=zzz_ia_desert_bushes,tag=5]
summon interaction -179 -37 10 {Tags:["zzz_ia_desert_bushes", "5"],height:1.1f,width:1.1f}
scoreboard players set P zzz_desert_bushes_progress 5
execute if score P zzz_desert_bushes_progress matches 6 run function escapemap:zzz/desert_bushes/complete
