#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/finish.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:laser/complete {p:"-163,-9,-50",tag:"castle_beam"}