#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/common.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:zzz/test/reset
function escapemap:zzz/test2/reset
