#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -31 -37 65 minecraft:lever[facing=south]
setblock -32 -38 64 air destroy
setblock -44 -37 55 oak_fence
setblock -51 -37 55 air
setblock -51 -35 55 barrier
schedule clear escapemap:puzzles/red_candle/fences/oak/expireblock
function escapemap:puzzles/red_candle/fences/oak/expireblock
setblock -42 -36 58 dark_oak_fence
setblock -44 -36 59 air
schedule clear escapemap:puzzles/red_candle/fences/dark/expirestencil
function escapemap:puzzles/red_candle/fences/dark/expirestencil
setblock -48 -36 63 warped_fence
setblock -48 -34 63 air
setblock -47 -36 64 air
setblock -47 -34 64 barrier
setblock -58 -36 67 warped_fence
setblock -49 -36 63 cherry_fence
setblock -49 -34 63 air
schedule clear escapemap:puzzles/red_candle/fences/birch/expireblock
function escapemap:puzzles/red_candle/fences/birch/expireblock
