#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/secret2_complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -23 -35 32 air
function escapemap:puzzles/secret_complete {p:"-23 -37 30"}
