#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/secret1_complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -51 -32 50 deepslate_tile_stairs[facing=east]
setblock -52 -33 50 minecraft:waxed_copper_bulb[lit=true]
function escapemap:puzzles/secret_complete {p:"-50 -28 50"}
