#######
# Compiled from escapemap/functions/area/areas.mcscript
# to .//data/escapemap/functions/area/unfreeze_items.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=item] if items entity @s contents *[minecraft:custom_data~{puzzle:{id:"ground"}}] run data modify entity @s PickupDelay set value 0s
