#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_03_pitch/frame_041.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:5,transformation:{translation:[0.000000f,3.193383f,-0.840257f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.600420f,0.000000f,0.000000f,0.799685f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:5,transformation:{translation:[0.000000f,3.193383f,-0.840257f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.600420f,0.000000f,0.000000f,0.799685f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
