#######
# Compiled from functions/puzzles/desert/faucet_controller.mcscript
# to .//data/escapemap/functions/puzzles/desert/faucet_controller/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -178 -38 67 air
setblock -178 -38 69 minecraft:waxed_oxidized_copper_bulb[lit=true]
function escapemap:puzzles/complete