#######
# Compiled from functions/puzzles/desert/faucet_controller.mcscript
# to .//data/escapemap/functions/puzzles/desert/faucet_controller/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######




