#######
# Compiled from functions/puzzles/desert/faucet_controller.mcscript
# to .//data/escapemap/functions/puzzles/desert/faucet_controller/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score F handle_cooldown matches 1.. run scoreboard players remove F handle_cooldown 1
execute if score F handle_cooldown matches 1.. run scoreboard players add F faucet_progress 1

execute if score F faucet_progress matches 2400.. if score P faucet_complete matches 0 run scoreboard players set F faucet_progress 2400
execute if score F faucet_progress matches 2400.. if score P faucet_complete matches 0 run function escapemap:puzzles/desert/faucet_controller/complete
execute if score F faucet_progress matches 2400.. if score P faucet_complete matches 0 run scoreboard players set P faucet_complete 1

scoreboard players add F faucet_ticker 1
execute if score F faucet_ticker matches 13.. run scoreboard players set F faucet_ticker 1

execute if score F faucet_progress matches ..200 positioned -178 -35.7 67.65 run particle minecraft:snowflake ~ ~ ~ 0 -2 0 0.1 0 normal

execute if score F faucet_progress matches 201..400 if score F faucet_ticker matches ..10 positioned -178 -35.7 67.65 run particle minecraft:snowflake ~ ~ ~ 0 -2 0 0.1 0 normal

execute if score F faucet_progress matches 401..700 if score F faucet_ticker matches ..8 positioned -178 -35.7 67.65 run particle minecraft:snowflake ~ ~ ~ 0 -2 0 0.1 0 normal

execute if score F faucet_progress matches 701..1000 if score F faucet_ticker matches ..6 positioned -178 -35.7 67.65 run particle minecraft:snowflake ~ ~ ~ 0 -2 0 0.1 0 normal

execute if score F faucet_progress matches 1001..1300 if score F faucet_ticker matches ..4 positioned -178 -35.7 67.65 run particle minecraft:snowflake ~ ~ ~ 0 -2 0 0.1 0 normal

execute if score F faucet_progress matches 1301..1700 if score F faucet_ticker matches ..3 positioned -178 -35.7 67.65 run particle minecraft:snowflake ~ ~ ~ 0 -2 0 0.1 0 normal

execute if score F faucet_progress matches 1701..2100 if score F faucet_ticker matches ..2 positioned -178 -35.7 67.65 run particle minecraft:snowflake ~ ~ ~ 0 -2 0 0.1 0 normal

execute if score F faucet_progress matches 2101..2399 if score F faucet_ticker matches 1 positioned -178 -35.7 67.65 run particle minecraft:snowflake ~ ~ ~ 0 -2 0 0.1 0 normal

