#######
# Compiled from functions/puzzles/castle/common.mcscript
# to .//data/escapemap/functions/puzzles/castle/onarmorstandinteract.mcfunction
#
# Generated by Minecraft Script for 1.16
######
advancement revoke @s only escapemap:armorstand_interaction