#######
# Compiled from functions/puzzles/castle/common.mcscript
# to .//data/escapemap/functions/puzzles/castle/oncauldron.mcfunction
#
# Generated by Minecraft Script for 1.16
######
advancement revoke @s only escapemap:cauldron_changed
function escapemap:puzzles/cyan_candle/basement/cauldron
function escapemap:puzzles/castle/tutorial/cauldron
function escapemap:puzzles/castle/hay1/cauldron
function escapemap:puzzles/castle/hay2/cauldron
function escapemap:puzzles/castle/hay3/cauldron
function escapemap:puzzles/castle/hay4/cauldron
function escapemap:puzzles/castle/smith/cauldron
function escapemap:puzzles/castle/targets/cauldron
function escapemap:puzzles/castle/targetsrev/cauldron
function escapemap:puzzles/castle/secrets/walltop/cauldron
