#######
# Compiled from functions/puzzles/castle/common.mcscript
# to .//data/escapemap/functions/puzzles/castle/oncomposter.mcfunction
#
# Generated by Minecraft Script for 1.16
######
advancement revoke @s only escapemap:composter_changed
function escapemap:puzzles/castle/farm/composter
