#######
# Compiled from functions/puzzles/castle/common.mcscript
# to .//data/escapemap/functions/puzzles/castle/onitemframe.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a run advancement revoke @s only escapemap:itemframe_use
function escapemap:puzzles/castle/pottery/onitemframe
function escapemap:puzzles/castle/waterarrows/onitemframe
function escapemap:puzzles/castle/towers/onitemframe
