#######
# Compiled from escapemap/functions/puzzles/actionbar.mcscript
# to .//data/escapemap/functions/puzzles/actionbar/radiation/20.mcfunction
#
# Generated by Minecraft Script for 1.16
######
title @s actionbar [{"text":"Radiation: [","color":"white"},{"text":"||||||||||||||||||||","color":"green"},{"text":"","color":"dark_gray"},{"text":"] ","color":"white"},{"score":{"name":"@s","objective":"rad_div"},"color":"white"},{"text":"%","color":"white"}]