#######
# Compiled from puzzles/castle/tower/door.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/door/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set P castle_tower_door_complete 0
setblock -163 -28 -48 air
setblock -163 -28 -49 air
setblock -163 -28 -50 air
setblock -163 -28 -50 air
setblock -163 -27 -50 air
setblock -164 -28 -48 air
setblock -164 -28 -48 crafter[orientation=down_east]
setblock -164 -27 -50 air
setblock -164 -27 -50 crafter[orientation=down_east]
setblock -164 -28 -50 minecraft:waxed_oxidized_copper_bulb[lit=false,powered=false]
