#######
# Compiled from puzzles/castle/tower/door.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/door/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P castle_tower_door_complete matches 0 run function escapemap:puzzles/castle/tower/door/check

