#######
# Compiled from castle/layer2/elevators/elevator.mcscript
# to .//data/escapemap/functions/puzzles/castle/layer2/elevators/elevator/arrive.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set #running escapemap_castle_elevator 0
scoreboard players operation #current_station escapemap_castle_elevator = #target_station escapemap_castle_elevator
execute if score #current_station escapemap_castle_elevator matches 0 run function escapemap:puzzles/castle/layer2/elevators/elevator/place_station_0_blocks
execute if score #current_station escapemap_castle_elevator matches 1 run function escapemap:puzzles/castle/layer2/elevators/elevator/place_station_1_blocks
execute if score #current_station escapemap_castle_elevator matches 2 run function escapemap:puzzles/castle/layer2/elevators/elevator/place_station_2_blocks
execute if score #current_station escapemap_castle_elevator matches 3 run function escapemap:puzzles/castle/layer2/elevators/elevator/place_station_3_blocks
execute as @a[x=-167.5,y=-59,z=-47.5,dx=10,dy=18,dz=10] at @s run tp @s ~ ~0.1 ~
function escapemap:puzzles/castle/layer2/elevators/elevator_listener/end
execute as @e[type=minecraft:shulker,tag=escapemap_castle_elevator] run data merge entity @s {Peek:0b,AttachFace:0b}
function escapemap:puzzles/castle/layer2/elevators/elevator/despawn_entities
