#######
# Compiled from castle/layer2/elevators/elevator.mcscript
# to .//data/escapemap/functions/puzzles/castle/layer2/elevators/elevator/despawn_entities.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=escapemap_castle_elevator] at @s run tp @s 0 -64 0
kill @e[type=minecraft:shulker,tag=escapemap_castle_elevator]
kill @e[type=minecraft:block_display,tag=escapemap_castle_elevator_display]
