#######
# Compiled from castle/layer2/elevators/elevator.mcscript
# to .//data/escapemap/functions/puzzles/castle/layer2/elevators/elevator/nudge_players.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a[x=-167.5,y=-59,z=-47.5,dx=10,dy=18,dz=10] at @s run tp @s ~ ~0.1 ~
