#######
# Compiled from castle/layer2/elevators/elevator.mcscript
# to .//data/escapemap/functions/puzzles/castle/layer2/elevators/elevator/stop.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set #running escapemap_castle_elevator 0
execute as @e[type=minecraft:shulker,tag=escapemap_castle_elevator] run data merge entity @s {Peek:0b,AttachFace:0b}
kill @e[type=minecraft:shulker,tag=escapemap_castle_elevator]
kill @e[type=minecraft:block_display,tag=escapemap_castle_elevator_display]
