#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/finish.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:laser/complete {p:"-169,-31,31",tag:"desert_beam"}