#######
# Compiled from functions/puzzles/castle/hay2.mcscript
# to .//data/escapemap/functions/puzzles/castle/hay2/cauldron.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if blocks -173 -37 -8 -175 -37 -8 -175 -40 -8 all run function escapemap:puzzles/castle/hay2/complete
