#######
# Compiled from functions/puzzles/red_candle/common.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/red_candle/fences/reset
function escapemap:puzzles/red_candle/attic/reset
function escapemap:puzzles/red_candle/cave/reset
function escapemap:puzzles/red_candle/elevator/reset
function escapemap:puzzles/red_candle/elevator_listener/reset
