#######
# Compiled from functions/puzzles/red_candle/common.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/red_candle/attic/tick