#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/kill.mcfunction
#
# Generated by Minecraft Script for 1.16
######
kill @e[tag=lighthouse]
function escapemap:laser/turn_off {tag:"lighthouse_beam"}
schedule clear escapemap:laser/lighthouse/finish
