#######
# Compiled from functions/super_secrets/lighthouse/controller.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/controller/begin_raycast.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set raycast1 ep_raycast 0
execute as @p at @s positioned ^ ^ ^30 run function escapemap:super_secrets/lighthouse/controller/raycast
