#######
# Compiled from functions/super_secrets/lighthouse/controller.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/controller/handle_active_tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score EP ep_active matches 1 run function escapemap:super_secrets/lighthouse/outline/tick_a
scoreboard players add EP ep_flash_timer 1
execute if score EP ep_flash_timer matches 20.. run scoreboard players set EP ep_flash_timer 0
execute if score EP ep_active matches 2 if score EP ep_flash_timer matches ..10 run function escapemap:super_secrets/lighthouse/outline/tick_a
execute if score EP ep_active matches 2 if score EP ep_flash_timer matches 10.. run function escapemap:super_secrets/lighthouse/outline/tick_b
execute as @e[tag=ep_cursor] if score @s ep_progress matches 10 run scoreboard players set EP ep_active 2
execute as @e[tag=ep_cursor] if score @s ep_progress matches ..9 run scoreboard players set EP ep_active 1
