#######
# Compiled from functions/super_secrets/lighthouse/controller.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/controller/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:super_secrets/lighthouse/outline/reset
data remove entity @e[tag=ep_input,limit=1] attack
attribute @p minecraft:movement_speed modifier remove ep



