#######
# Compiled from functions/super_secrets/lighthouse/controller.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/controller/raycast.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players add raycast1 ep_raycast 1
execute positioned ^ ^ ^1 if entity @e[tag=ep_start,limit=1,distance=..5,sort=nearest] run tag @s add raycast_stop
execute positioned ^ ^ ^1 if entity @e[tag=ep_end,limit=1,distance=..2,sort=nearest] run tag @s add raycast_stop
execute positioned ^ ^ ^1 if entity @e[tag=ep_start,limit=1,distance=..5,sort=nearest] run function escapemap:super_secrets/lighthouse/controller/raycast_start_hit
execute positioned ^ ^ ^1 if entity @e[tag=ep_end,limit=1,distance=..2,sort=nearest] run function escapemap:super_secrets/lighthouse/controller/raycast_end_hit
execute positioned ^ ^ ^1 if entity @s[tag=!raycast_stop] if block ~ ~ ~ air if score raycast1 ep_raycast matches ..70 run function escapemap:super_secrets/lighthouse/controller/raycast
execute positioned ^ ^ ^1 if entity @s[tag=!raycast_stop] unless block ~ ~ ~ air run function escapemap:super_secrets/lighthouse/controller/raycast_fail
execute positioned ^ ^ ^1 if entity @s[tag=!raycast_stop] if block ~ ~ ~ air if score raycast1 ep_raycast matches 71.. run function escapemap:super_secrets/lighthouse/controller/raycast_fail
tag @s[tag=raycast_stop] remove raycast_stop
