#######
# Compiled from functions/super_secrets/lighthouse/controller.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/controller/raycast_end_hit.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say hit end
execute store result storage escapemap:tmp raycast int 1 run scoreboard players get EP ep_active
execute if data storage escapemap:tmp {raycast:2} run scoreboard players set EP ep_active 3
execute unless data storage escapemap:tmp {raycast:2} run scoreboard players set EP ep_active 0
execute if data storage escapemap:tmp {raycast:2} run function escapemap:super_secrets/lighthouse/controller/complete
attribute @p minecraft:movement_speed modifier remove ep
