#######
# Compiled from functions/super_secrets/lighthouse/controller.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/controller/raycast_start_hit.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute store result storage escapemap:tmp raycast int 1 run scoreboard players get EP ep_active
execute if data storage escapemap:tmp {raycast:0} run scoreboard players set EP ep_active 1
execute if data storage escapemap:tmp {raycast:0} run function escapemap:super_secrets/lighthouse/outline/reset
execute if data storage escapemap:tmp {raycast:0} run attribute @p minecraft:movement_speed modifier add ep -1.0 add_value
execute unless data storage escapemap:tmp {raycast:0} run scoreboard players set EP ep_active 0
execute unless data storage escapemap:tmp {raycast:0} run attribute @p minecraft:movement_speed modifier remove ep
