#######
# Compiled from functions/super_secrets/lighthouse/controller.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/controller/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data remove entity @e[tag=ep_input,limit=1] attack
data remove entity @e[tag=ep_input,limit=1] interaction
scoreboard players set EP ep_active 0
scoreboard players set EP ep_flash_timer 0
scoreboard players set raycast1 ep_raycast 0
