#######
# Compiled from functions/super_secrets/lighthouse/controller.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/controller/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if entity @e[tag=ep_input,nbt={attack:{}}] if score EP ep_active matches ..2 run function escapemap:super_secrets/lighthouse/controller/begin_raycast
execute if entity @e[tag=ep_input,nbt={attack:{}}] run data remove entity @e[tag=ep_input,limit=1] attack

execute if score EP ep_active matches 1..2 run function escapemap:super_secrets/lighthouse/controller/handle_active_tick
execute if score EP ep_active matches 3 run function escapemap:super_secrets/lighthouse/outline/tick_fixed
