#######
# Compiled from escapemap/functions/laser/common.mcscript
# to .//data/escapemap/functions/laser/complete_laser.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:laser/animation
schedule escapemap:thingy/enable_laser 200 replace
