#######
# Compiled from escapemap/functions/laser/common.mcscript
# to .//data/escapemap/functions/laser/enable_laser.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:laser/complete {p:"90 -25 90",tag:"mytesttag"}
