#######
# Compiled from escapemap/functions/laser/common.mcscript
# to .//data/escapemap/functions/laser/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @a lasers_complete 0
