#######
# Compiled from .//functions/output2.mcscript
# to elevator/arrive.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set #running escapemap_nexus_lift 0
execute if score #dir_sign escapemap_nexus_lift matches 1 run function escapemap:mechanical/elevators/elevator/place_top_blocks
execute if score #dir_sign escapemap_nexus_lift matches -1 run function escapemap:mechanical/elevators/elevator/place_bottom_blocks
execute as @a[x=9.5,y=-27,z=-17.5,dx=4,dy=11,dz=4] at @s run tp @s ~ ~0.1 ~
function escapemap:mechanical/elevators/elevator_listener/end
execute as @e[type=minecraft:shulker,tag=escapemap_nexus_lift] run data merge entity @s {Peek:0b,AttachFace:0b}
function escapemap:mechanical/elevators/elevator/despawn_entities
