#######
# Compiled from .//functions/output2.mcscript
# to elevator/despawn_entities.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=escapemap_nexus_lift] at @s run tp @s 0 -64 0
kill @e[type=minecraft:shulker,tag=escapemap_nexus_lift]
kill @e[type=minecraft:block_display,tag=escapemap_nexus_lift_display]
