#######
# Compiled from .//functions/output2.mcscript
# to elevator/finish_a.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #dir_sign escapemap_nexus_lift matches 1 as @e[type=minecraft:shulker,tag=escapemap_nexus_lift_b] at @s run tp @s ~ ~2 ~
execute if score #dir_sign escapemap_nexus_lift matches -1 as @e[type=minecraft:shulker,tag=escapemap_nexus_lift_b] at @s run tp @s ~ ~-2 ~
execute as @e[type=minecraft:shulker,tag=escapemap_nexus_lift_a,limit=1] at @s run function escapemap:mechanical/elevators/elevator/nudge_players
execute as @e[type=minecraft:shulker,tag=escapemap_nexus_lift_a] run data merge entity @s {Peek:0b,AttachFace:0b}
scoreboard players set #a escapemap_nexus_lift 0
scoreboard players set #active escapemap_nexus_lift 1
scoreboard players add #cycle escapemap_nexus_lift 1
execute if score #cycle escapemap_nexus_lift >= #max_cycles escapemap_nexus_lift run function escapemap:mechanical/elevators/elevator/arrive
