#######
# Compiled from .//functions/output2.mcscript
# to elevator/force_attach_face.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:shulker,tag=escapemap_nexus_lift] run data merge entity @s {AttachFace:0b}
