#######
# Compiled from .//functions/output2.mcscript
# to elevator/go_down.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #running escapemap_nexus_lift matches 0 run function escapemap:mechanical/elevators/elevator/start_down
