#######
# Compiled from .//functions/output2.mcscript
# to elevator/place_top_blocks.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock 11 -20 -16 minecraft:chiseled_polished_blackstone
setblock 12 -20 -16 minecraft:polished_blackstone_slab[type=top]
setblock 10 -20 -16 minecraft:polished_blackstone_slab[type=top]
setblock 11 -20 -15 minecraft:polished_blackstone_slab[type=top]
setblock 11 -20 -17 minecraft:polished_blackstone_slab[type=top]
