#######
# Compiled from .//functions/output2.mcscript
# to elevator/start_up.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set #dir_sign escapemap_nexus_lift 1
scoreboard players set #max_cycles escapemap_nexus_lift 5
scoreboard players set #a escapemap_nexus_lift 0
scoreboard players set #b escapemap_nexus_lift 0
scoreboard players set #active escapemap_nexus_lift 0
scoreboard players set #cycle escapemap_nexus_lift 0
scoreboard players set #tick escapemap_nexus_lift 0
scoreboard players set #running escapemap_nexus_lift 1
function escapemap:mechanical/elevators/elevator_listener/start
setblock 11 -25 -16 minecraft:air
setblock 12 -25 -16 minecraft:air
setblock 10 -25 -16 minecraft:air
setblock 11 -25 -15 minecraft:air
setblock 11 -25 -17 minecraft:air
summon minecraft:shulker 11.5 -25 -15.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:14b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker 12.5 -25 -15.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:14b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker 10.5 -25 -15.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:14b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker 11.5 -25 -14.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:14b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker 11.5 -25 -16.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:14b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker 11.5 -26 -15.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:15b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker 12.5 -26 -15.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:15b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker 10.5 -26 -15.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:15b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker 11.5 -26 -14.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:15b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker 11.5 -26 -16.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:15b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:block_display 11.5 -24 -15.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_display"],block_state:{Name:"minecraft:chiseled_polished_blackstone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display 12.5 -24 -15.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_display"],block_state:{Name:"minecraft:polished_blackstone_slab",Properties:{type:"top"}},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display 10.5 -24 -15.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_display"],block_state:{Name:"minecraft:polished_blackstone_slab",Properties:{type:"top"}},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display 11.5 -24 -14.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_display"],block_state:{Name:"minecraft:polished_blackstone_slab",Properties:{type:"top"}},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display 11.5 -24 -16.5 {Tags:["escapemap_nexus_lift","escapemap_nexus_lift_display"],block_state:{Name:"minecraft:polished_blackstone_slab",Properties:{type:"top"}},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
execute as @a[x=9.5,y=-27,z=-17.5,dx=4,dy=11,dz=4] at @s run tp @s ~ ~0.1 ~
