#######
# Compiled from .//functions/output2.mcscript
# to elevator/stop.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set #running escapemap_nexus_lift 0
execute as @e[type=minecraft:shulker,tag=escapemap_nexus_lift] run data merge entity @s {Peek:0b,AttachFace:0b}
kill @e[type=minecraft:shulker,tag=escapemap_nexus_lift]
kill @e[type=minecraft:block_display,tag=escapemap_nexus_lift_display]
