#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/finish.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:laser/complete {p:"-169,-31,31",tag:"desert_beam"}