#######
# Compiled from puzzles/castle/layer2/layer2.mcscript
# to .//data/escapemap/functions/puzzles/castle/layer2/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/castle/layer2/well/tick
function escapemap:puzzles/castle/layer2/elevators/controller/tick