#######
# Compiled from data/escapemap/functions/items.mcscript
# to .//data/escapemap/functions/items/castle_stair.mcfunction
#
# Generated by Minecraft Script for 1.16
######
give @s minecraft:oak_stairs[minecraft:custom_name='{"text":"Missing tower stair","italic":false}',minecraft:custom_data={puzzle:{id:"castle_stair","persistent":1b}}] 1