#######
# Compiled from data/escapemap/functions/items.mcscript
# to .//data/escapemap/functions/items/village_yard_redstone.mcfunction
#
# Generated by Minecraft Script for 1.16
######
give @s minecraft:redstone[minecraft:custom_data={puzzle:{id:"village_yard","persistent":1b}}] 1