# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_spout) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.7531f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 10}
$data merge entity $(bone_housing) {transformation: [-1.6875f,0f,0f,0f,0f,1.6875f,0f,1.8156f,0f,0f,-1.6875f,-1.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 10}
$data merge entity $(bone_laser) {transformation: [-1.5833f,0f,0f,0f,0f,1.5833f,0f,2.5656f,0f,0f,-1.5833f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 10}
$data merge entity $(bone_extruder) {transformation: [-1.625f,0f,0f,0f,0f,1.625f,0f,1.1281f,0f,0f,-1.625f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 10}