#######
# Compiled from functions/puzzles/jungle/map_parts.mcscript
# to .//data/escapemap/functions/puzzles/jungle/map_parts/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
clone -125 -48 112 -125 -48 112 37 -20 105
clone -125 -48 111 -125 -48 111 33 -19 89
clone -125 -48 110 -125 -48 110 56 -15 92
clone -125 -48 109 -125 -48 109 52 -20 99