#######
# Compiled from escapemap/functions/area/areas.mcscript
# to .//data/escapemap/functions/area/areas/changed.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score @s area matches 0 run function escapemap:area/areas/neutral
execute if score @s area matches 1 run function escapemap:area/areas/village_yard
execute if score @s area matches 2 run function escapemap:area/areas/spawn_tutorial
execute if score @s area matches 3 run function escapemap:area/areas/village_cyan
execute if score @s area matches 4 run function escapemap:area/areas/castle
execute if score @s area matches 5 run function escapemap:area/areas/basement
execute if score @s area matches 6 run function escapemap:area/areas/mini_cave
execute if score @s area matches 7 run function escapemap:area/areas/desert
