#######
# Compiled from escapemap/functions/area/areas.mcscript
# to .//data/escapemap/functions/area/areas/inventory_changed.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:area/areas/changed
function escapemap:area/items/candle_flint_and_steel
advancement revoke @s only escapemap:inventory_changed