#######
# Compiled from escapemap/functions/area/areas.mcscript
# to .//data/escapemap/functions/area/areas/mini_cave.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:area/items/multitool_mini_cave
