#######
# Compiled from escapemap/functions/area/areas.mcscript
# to .//data/escapemap/functions/area/areas/neutral.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:area/items/multitool_neutral
function escapemap:area/items/village_yard_redstone_neutral
