#######
# Compiled from escapemap/functions/area/areas.mcscript
# to .//data/escapemap/functions/area/areas/village_yard.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:area/items/multitool_village_yard
function escapemap:area/items/village_yard_redstone_active
