#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/cherry/press.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute store success storage escapemap:tmp isFence byte 1 if block -49 -36 63 cherry_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -49 -36 63 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -49 -34 63 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -49 -36 63 air run setblock -49 -36 63 cherry_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -49 -34 63 air
