#######
# Compiled from functions/puzzles/desert/ruins.mcscript
# to .//data/escapemap/functions/puzzles/desert/ruins/check.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score R ruins_complete matches 0 if block -182 -30 64 waxed_oxidized_copper_bulb[lit=true] run setblock -181 -31 64 air
execute if score R ruins_complete matches 0 if block -182 -30 64 waxed_oxidized_copper_bulb[lit=true] run function escapemap:puzzles/complete
execute if score R ruins_complete matches 0 if block -182 -30 64 waxed_oxidized_copper_bulb[lit=true] run scoreboard players set R ruins_complete 1
