#######
# Compiled from functions/puzzles/desert/ruins.mcscript
# to .//data/escapemap/functions/puzzles/desert/ruins/leaves_update.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute unless block -182 -35 63 pale_oak_leaves run setblock -182 -36 63 red_terracotta
execute if block -182 -35 63 pale_oak_leaves run setblock -182 -36 63 redstone_block
execute unless block -182 -35 63 pale_oak_leaves unless block -184 -36 64 redstone_wire[power=5] run setblock -183 -32 63 barrier
execute if block -182 -35 63 pale_oak_leaves run setblock -183 -32 63 air
execute unless block -185 -36 62 pale_oak_leaves run setblock -185 -37 62 red_terracotta
execute if block -185 -36 62 pale_oak_leaves run setblock -185 -37 62 redstone_block
execute unless block -185 -36 62 air run setblock -185 -34 62 air
execute if block -185 -36 62 air run setblock -185 -34 62 barrier
execute unless block -185 -36 58 air run setblock -185 -34 58 air
execute if block -185 -36 58 air run setblock -185 -34 58 barrier
execute unless block -178 -34 64 air run setblock -178 -32 64 air
execute if block -178 -34 64 air run setblock -178 -32 64 barrier
execute if block -178 -34 64 pale_oak_leaves run setblock -178 -34 64 oak_leaves
