#######
# Compiled from functions/puzzles/desert/ruins.mcscript
# to .//data/escapemap/functions/puzzles/desert/ruins/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set R ruins_complete 0
setblock -185 -36 62 air
setblock -185 -36 58 air
setblock -182 -35 63 air
setblock -178 -34 64 air
function escapemap:puzzles/desert/ruins/leaves_update
setblock -182 -30 64 waxed_oxidized_copper_bulb[lit=false,powered=false]
setblock -181 -31 64 stone_button[facing=east]
clone -125 -48 114 -125 -48 114 -178 -32 53
clone -125 -48 113 -125 -48 113 -191 -29 51
