#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_01_flaps/frame_189.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,1.123422f,-3.446024f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.891452f,0.000000f,0.000000f,-0.453116f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,1.123422f,3.446024f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.891452f,0.000000f,0.000000f,-0.453116f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
