#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_01_flaps/frame_167.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.077088f,-3.367199f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.973053f,0.000000f,0.000000f,-0.230580f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.077088f,3.367199f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.973053f,0.000000f,0.000000f,-0.230580f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
