#######
# Compiled from escapemap/functions/ep/desert_tut.mcscript
# to .//data/escapemap/functions/ep/desert_tut/click_4.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=ep_ia_desert_tut,tag=4] run data remove entity @s interaction
kill @e[tag=ep_ia_desert_tut,tag=5]
summon interaction -154 -47 43 {Tags:["ep_ia_desert_tut", "5"],height:1.1f,width:1.1f}
scoreboard players set P ep_desert_tut_progress 5
execute if score P ep_desert_tut_progress matches 6 run function escapemap:ep/desert_tut/complete
