#######
# Compiled from escapemap/functions/ep/desert_tut.mcscript
# to .//data/escapemap/functions/ep/desert_tut/particle_1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:dust{color:[1,1,1],scale:1} -149.5 -46.0 46.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -149.5 -46.0 45.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -149.5 -46.0 44.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -149.5 -46.0 43.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -149.5 -46.0 42.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -149.5 -46.0 41.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -149.5 -46.0 40.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -149.5 -46.0 39.5 0.5 0 0.5 0 1
