#######
# Compiled from escapemap/functions/ep/desert_tut.mcscript
# to .//data/escapemap/functions/ep/desert_tut/summon0.mcfunction
#
# Generated by Minecraft Script for 1.16
######
summon interaction -150 -47 46 {Tags:["ep_ia_desert_tut", "0"],height:1.1f,width:1.1f}
