#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_06_yaw/frame_060.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.172563f,3.437500f,-0.180892f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.656424f,-0.262883f,0.262883f,0.656424f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.431407f,3.437500f,-0.452231f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.656424f,-0.262883f,0.262883f,0.656424f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
