#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_06_yaw/frame_105.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.242977f,3.437500f,-0.058839f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.555732f,-0.437220f,0.437220f,0.555732f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.607444f,3.437500f,-0.147096f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.555732f,-0.437220f,0.437220f,0.555732f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
