#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_06_yaw/frame_120.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.249722f,3.437500f,-0.011777f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.511641f,-0.488081f,0.488081f,0.511641f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.624306f,3.437500f,-0.029442f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.511641f,-0.488081f,0.488081f,0.511641f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
