#######
# Compiled from puzzles/desert/lights/tutorial3.mcscript
# to .//data/escapemap/functions/puzzles/desert/lights/pp5/toggle.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data modify storage escapemap:tmp isStone set value 0b
execute if block ~ ~2 ~-1 redstone_wire positioned ~ ~2 ~-2 unless entity @e[tag=pp5_fake,distance=..1] run data modify storage escapemap:tmp isStone set value 1b
execute if block ~ ~2 ~-1 redstone_wire if data storage escapemap:tmp {isStone:1b} positioned ~ ~2 ~-2 run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["pp5_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if block ~ ~2 ~-1 redstone_wire if data storage escapemap:tmp {isStone:0b} positioned ~ ~2 ~-2 as @e[tag=pp5_fake,distance=..1] run kill @s
execute positioned ~ ~2 ~-1 positioned ~ ~-1 ~ if block ~ ~ ~ sandstone positioned ~ ~2 ~-1 positioned ~ ~-1 ~ unless entity @e[tag=pp5_fake,distance=..1] run data modify storage escapemap:tmp isStone set value 1b
execute positioned ~ ~2 ~-1 positioned ~ ~-1 ~ if block ~ ~ ~ sandstone if data storage escapemap:tmp {isStone:1b} positioned ~ ~2 ~-1 positioned ~ ~-1 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["pp5_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute positioned ~ ~2 ~-1 positioned ~ ~-1 ~ if block ~ ~ ~ sandstone if data storage escapemap:tmp {isStone:0b} positioned ~ ~2 ~-1 positioned ~ ~-1 ~ as @e[tag=pp5_fake,distance=..1] run kill @s
data modify storage escapemap:tmp isStone set value 0b
execute if block ~ ~2 ~1 redstone_wire positioned ~ ~2 ~2 unless entity @e[tag=pp5_fake,distance=..1] run data modify storage escapemap:tmp isStone set value 1b
execute if block ~ ~2 ~1 redstone_wire if data storage escapemap:tmp {isStone:1b} positioned ~ ~2 ~2 run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["pp5_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if block ~ ~2 ~1 redstone_wire if data storage escapemap:tmp {isStone:0b} positioned ~ ~2 ~2 as @e[tag=pp5_fake,distance=..1] run kill @s
execute positioned ~ ~2 ~1 positioned ~ ~-1 ~ if block ~ ~ ~ sandstone positioned ~ ~2 ~1 positioned ~ ~-1 ~ unless entity @e[tag=pp5_fake,distance=..1] run data modify storage escapemap:tmp isStone set value 1b
execute positioned ~ ~2 ~1 positioned ~ ~-1 ~ if block ~ ~ ~ sandstone if data storage escapemap:tmp {isStone:1b} positioned ~ ~2 ~1 positioned ~ ~-1 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["pp5_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute positioned ~ ~2 ~1 positioned ~ ~-1 ~ if block ~ ~ ~ sandstone if data storage escapemap:tmp {isStone:0b} positioned ~ ~2 ~1 positioned ~ ~-1 ~ as @e[tag=pp5_fake,distance=..1] run kill @s
data modify storage escapemap:tmp isStone set value 0b
execute if block ~-1 ~2 ~ redstone_wire positioned ~-2 ~2 ~ unless entity @e[tag=pp5_fake,distance=..1] run data modify storage escapemap:tmp isStone set value 1b
execute if block ~-1 ~2 ~ redstone_wire if data storage escapemap:tmp {isStone:1b} positioned ~-2 ~2 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["pp5_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if block ~-1 ~2 ~ redstone_wire if data storage escapemap:tmp {isStone:0b} positioned ~-2 ~2 ~ as @e[tag=pp5_fake,distance=..1] run kill @s
execute positioned ~-1 ~2 ~ positioned ~ ~-1 ~ if block ~ ~ ~ sandstone positioned ~-1 ~2 ~ positioned ~ ~-1 ~ unless entity @e[tag=pp5_fake,distance=..1] run data modify storage escapemap:tmp isStone set value 1b
execute positioned ~-1 ~2 ~ positioned ~ ~-1 ~ if block ~ ~ ~ sandstone if data storage escapemap:tmp {isStone:1b} positioned ~-1 ~2 ~ positioned ~ ~-1 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["pp5_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute positioned ~-1 ~2 ~ positioned ~ ~-1 ~ if block ~ ~ ~ sandstone if data storage escapemap:tmp {isStone:0b} positioned ~-1 ~2 ~ positioned ~ ~-1 ~ as @e[tag=pp5_fake,distance=..1] run kill @s
data modify storage escapemap:tmp isStone set value 0b
execute if block ~1 ~2 ~ redstone_wire positioned ~2 ~2 ~ unless entity @e[tag=pp5_fake,distance=..1] run data modify storage escapemap:tmp isStone set value 1b
execute if block ~1 ~2 ~ redstone_wire if data storage escapemap:tmp {isStone:1b} positioned ~2 ~2 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["pp5_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if block ~1 ~2 ~ redstone_wire if data storage escapemap:tmp {isStone:0b} positioned ~2 ~2 ~ as @e[tag=pp5_fake,distance=..1] run kill @s
execute positioned ~1 ~2 ~ positioned ~ ~-1 ~ if block ~ ~ ~ sandstone positioned ~1 ~2 ~ positioned ~ ~-1 ~ unless entity @e[tag=pp5_fake,distance=..1] run data modify storage escapemap:tmp isStone set value 1b
execute positioned ~1 ~2 ~ positioned ~ ~-1 ~ if block ~ ~ ~ sandstone if data storage escapemap:tmp {isStone:1b} positioned ~1 ~2 ~ positioned ~ ~-1 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["pp5_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute positioned ~1 ~2 ~ positioned ~ ~-1 ~ if block ~ ~ ~ sandstone if data storage escapemap:tmp {isStone:0b} positioned ~1 ~2 ~ positioned ~ ~-1 ~ as @e[tag=pp5_fake,distance=..1] run kill @s
data modify storage escapemap:tmp isStone set value 0b
execute positioned ~ ~2 ~ unless entity @e[tag=pp5_fake,distance=..1] run data modify storage escapemap:tmp isStone set value 1b
execute if data storage escapemap:tmp {isStone:1b} positioned ~ ~2 ~ run summon minecraft:block_display ~-0.5 ~-0.5 ~-0.5 {Tags:["pp5_fake"],block_state:{Name:"minecraft:light_weighted_pressure_plate"},transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.025f,0.0f,-0.025f],scale:[1.05f,1.05f,1.05f]}}
execute if data storage escapemap:tmp {isStone:0b} positioned ~ ~2 ~ as @e[tag=pp5_fake,distance=..1] run kill @s
scoreboard players set C desert_pp5 0
execute as @e[tag=pp5_fake] run scoreboard players add C desert_pp5 1
execute if score C desert_pp5 matches 16 run function escapemap:puzzles/desert/lights/pp5/complete

