#######
# Compiled from puzzles/castle/tower/lecterns.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/lecterns/check.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set C castle_lecterns_completed 0
execute if data block -160 -24 -52 {Page: 0} run scoreboard players add C castle_lecterns_completed 1

execute if data block -160 -24 -50 {Page: 1} run scoreboard players add C castle_lecterns_completed 1

execute if data block -161 -24 -48 {Page: 2} run scoreboard players add C castle_lecterns_completed 1

execute if data block -166 -24 -48 {Page: 0} run scoreboard players add C castle_lecterns_completed 1

execute if data block -166 -24 -50 {Page: 2} run scoreboard players add C castle_lecterns_completed 1

execute if data block -166 -24 -52 {Page: 1} run scoreboard players add C castle_lecterns_completed 1

execute if score C castle_lecterns_completed matches 6 run function escapemap:puzzles/castle/tower/lecterns/complete

