#######
# Compiled from puzzles/castle/tower/lecterns.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/lecterns/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set P castle_lecterns_completed 0
setblock -163 -24 -47 minecraft:waxed_oxidized_copper_bulb[powered=false,lit=false]
setblock -163 -23 -48 minecraft:iron_trapdoor[open=true]
setblock -163 -21 -48 barrier
data merge block -160 -24 -52 {Page: 2}
data merge block -160 -24 -50 {Page: 0}
data merge block -161 -24 -48 {Page: 1}
data merge block -166 -24 -48 {Page: 1}
data merge block -166 -24 -50 {Page: 0}
data merge block -166 -24 -52 {Page: 2}
