#######
# Compiled from functions/puzzles/red_candle/attic.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/attic/break.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -31 -34 68 air