#######
# Compiled from functions/puzzles/red_candle/attic.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/attic/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/complete
setblock -34 -34 64 air
