#######
# Compiled from functions/puzzles/red_candle/attic.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/attic/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if entity @e[tag=attic_breakable,nbt={attack:{}}] run function escapemap:puzzles/red_candle/attic/break
execute if entity @e[tag=attic_breakable,nbt={attack:{}}] run kill @e[tag=attic_breakable]

