#######
# Compiled from functions/puzzles/desert/cave.mcscript
# to .//data/escapemap/functions/puzzles/desert/cave/check.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set C desert_cave 0
execute as @e[tag=pp_cave_fake] run scoreboard players add C desert_cave 1
execute if score C desert_cave matches 8 run function escapemap:puzzles/desert/cave/complete

