# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.laser_open.frame matches 2001.. run scoreboard players set @s aj.laser_open.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.laser_open.frame
execute at @s run function animated_java:escapemap_laser/animations/laser_open/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.laser_open.frame 1