#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/oak/expirestencil.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -46 -36 60 air
setblock -46 -34 60 barrier