#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/oak/expireblock.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -54 -36 65 oak_wood
setblock -54 -34 65 air
