#######
# Compiled from functions/puzzles/red_candle/cave.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/cave/oak/press.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute store success storage escapemap:tmp isFence byte 1 if block -58 -45 65 oak_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -58 -45 65 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -58 -43 65 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -58 -45 65 air run setblock -58 -45 65 oak_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -58 -43 65 air
execute store success storage escapemap:tmp isFence byte 1 if block -57 -45 74 oak_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -57 -45 74 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -57 -47 74 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -57 -45 74 air run setblock -57 -45 74 oak_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -57 -47 74 air
execute store success storage escapemap:tmp isFence byte 1 if block -43 -45 67 oak_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -43 -45 67 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -43 -43 67 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -43 -45 67 air run setblock -43 -45 67 oak_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -43 -43 67 air
execute store success storage escapemap:tmp isFence byte 1 if block -43 -45 64 oak_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -43 -45 64 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -43 -43 64 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -43 -45 64 air run setblock -43 -45 64 oak_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -43 -43 64 air
execute store success storage escapemap:tmp isFence byte 1 if block -62 -43 71 oak_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -62 -43 71 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -62 -45 71 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -62 -43 71 air run setblock -62 -43 71 oak_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -62 -45 71 air
execute store success storage escapemap:tmp isFence byte 1 if block -61 -45 67 oak_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -61 -45 67 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -61 -47 67 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -61 -45 67 air run setblock -61 -45 67 oak_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -61 -47 67 air
