#######
# Compiled from functions/puzzles/castle/targets_rev.mcscript
# to .//data/escapemap/functions/puzzles/castle/targetsrev/cauldron.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if blocks -166 -38 -36 -166 -38 -32 -166 -41 -36 all run function escapemap:puzzles/castle/targetsrev/complete
