#######
# Compiled from functions/puzzles/castle/targets_rev.mcscript
# to .//data/escapemap/functions/puzzles/castle/targetsrev/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
fill -166 -38 -36 -166 -38 -32 cauldron
scoreboard players set P puzzle_castle_targets_rev_complete 0
setblock -166 -38 -34 minecraft:waxed_oxidized_copper_bulb[lit=false,powered=false]
