#######
# Compiled from /functions/output/faucet.mcscript
# to .//functions/output/faucet/attach_handle.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @p if items entity @s weapon.mainhand minecraft:paper[minecraft:item_model="escapemap:faucet_handle"] run summon minecraft:item_display -177.500 -34.800 68.200 {Rotation:[180.0f,0f],Tags:["faucet_part","escapemap_faucet_handle"],item:{id:"minecraft:paper",count:1,components:{"minecraft:item_model": "escapemap:faucet_handle"}},item_display:"fixed",brightness:{block:15,sky:15}}
execute as @p if items entity @s weapon.mainhand minecraft:paper[minecraft:item_model="escapemap:faucet_handle"] run tag @e[tag=escapemap_faucet_base,limit=1] add handle_attached
execute as @p if items entity @s weapon.mainhand minecraft:paper[minecraft:item_model="escapemap:faucet_handle"] run clear @s minecraft:paper[minecraft:item_model="escapemap:faucet_handle"] 1
