#######
# Compiled from /functions/output/faucet.mcscript
# to .//functions/output/faucet/main_tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=faucet_interaction,nbt={interaction:{}}] at @s as @e[tag=escapemap_faucet_base,tag=!handle_attached,limit=1] run function escapemap:puzzles/desert/faucet/attach_handle
execute as @e[tag=faucet_interaction,nbt={interaction:{}}] at @s if entity @e[tag=escapemap_faucet_base,tag=handle_attached,limit=1] run function escapemap:puzzles/desert/faucet/rotate_handle
execute as @e[tag=faucet_interaction,nbt={interaction:{}}] run data remove entity @s interaction
