#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_06_yaw/frame_059.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.159517f,3.437500f,-0.192495f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.665203f,-0.239803f,0.239803f,0.665203f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.398793f,3.437500f,-0.481237f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.665203f,-0.239803f,0.239803f,0.665203f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
