#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_06_yaw/frame_041.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.115638f,3.437500f,-0.221648f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.686766f,-0.168381f,0.168381f,0.686766f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.289096f,3.437500f,-0.554120f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.686766f,-0.168381f,0.168381f,0.686766f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
