#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_06_yaw/frame_035.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.099767f,3.437500f,-0.229230f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.692265f,-0.144117f,0.144117f,0.692265f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.249418f,3.437500f,-0.573076f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.692265f,-0.144117f,0.144117f,0.692265f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
