#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_06_yaw/frame_081.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.203356f,3.437500f,-0.145417f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.628822f,-0.323393f,0.323393f,0.628822f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.508391f,3.437500f,-0.363543f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.628822f,-0.323393f,0.323393f,0.628822f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
