#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_06_yaw/frame_012.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.035070f,3.437500f,-0.247528f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.705357f,-0.049719f,0.049719f,0.705357f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.087674f,3.437500f,-0.618820f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.705357f,-0.049719f,0.049719f,0.705357f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
