#######
# Compiled from data/escapemap/functions/containers.mcscript
# to .//data/escapemap/functions/containers/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data remove block -53 -37 49 Items
data remove block -35 -37 38 Items
data remove block -35 -37 37 Items
data remove block -35 -37 36 Items
data remove block -35 -37 35 Items
data remove block -35 -37 62 Items
data remove block -129 -32 120 Items
data remove block -129 -32 120 Items
data remove block -118 -38 98 Items
data remove block -88 -22 -39 Items
data remove block -87 -21 -39 Items
data remove block -85 -22 -43 Items
data remove block -85 -22 -42 Items
data remove block -85 -22 -41 Items
data remove block -85 -21 -41 Items
data remove block -87 -22 -39 Items
data remove block -85 -22 -39 Items
data remove block -86 -22 -39 Items
data remove block -85 -27 -41 Items
data remove block -163 -37 -6 Items
data remove block -176 -32 -16 Items
data remove block -177 -32 -16 Items
data remove block -180 -37 -27 Items
data remove block -180 -37 -28 Items
data remove block -180 -37 -29 Items
data remove block -180 -37 -30 Items
data remove block -178 -37 -57 Items
data remove block -109 -37 40 Items
data remove block -168 -37 -47 Items
data remove block -112 -37 40 Items
