#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/turn_on.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:laser/castle/reset
function escapemap:laser/castle/step_01_flaps
schedule function escapemap:laser/castle/step_02_up 600t
schedule function escapemap:laser/castle/step_03_pitch 1250t
schedule function escapemap:laser/castle/step_04_z_pull 1700t
schedule function escapemap:laser/castle/step_05_spout_extend 1950t
schedule function escapemap:laser/castle/step_06_yaw 2200t
schedule function escapemap:laser/castle/step_07_pitch 2600t
schedule function escapemap:laser/castle/finish 2650t
