#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_03_pitch/frame_046.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.716390f,-0.495605f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.296542f,0.000000f,0.000000f,0.955020f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.716390f,-0.495605f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.296542f,0.000000f,0.000000f,0.955020f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
