#######
# Compiled from functions/puzzles/red_candle/cave.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/cave/mangroove/press.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute store success storage escapemap:tmp isFence byte 1 if block -49 -45 65 mangrove_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -49 -45 65 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -49 -43 65 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -49 -45 65 air run setblock -49 -45 65 mangrove_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -49 -43 65 air
execute store success storage escapemap:tmp isFence byte 1 if block -51 -45 63 mangrove_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -51 -45 63 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -51 -43 63 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -51 -45 63 air run setblock -51 -45 63 mangrove_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -51 -43 63 air
