#######
# Compiled from functions/super_secrets/lighthouse/trail.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/trail/kill.mcfunction
#
# Generated by Minecraft Script for 1.16
######
kill @e[tag=ss_trail_lighthouse]
kill @e[tag=ss_trail_lighthouse_end]
