#######
# Compiled from functions/super_secrets/lighthouse/trail.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/trail/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @a lighthouse_trail 0
