#######
# Compiled from escapemap/functions/ep/desert_bushes.mcscript
# to .//data/escapemap/functions/ep/desert_bushes/click_2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=ep_ia_desert_bushes,tag=2] run data remove entity @s interaction
kill @e[tag=ep_ia_desert_bushes,tag=3]
kill @e[tag=ep_ia_desert_bushes,tag=4]
kill @e[tag=ep_ia_desert_bushes,tag=5]
summon interaction -175 -37 15 {Tags:["ep_ia_desert_bushes", "3"],height:1.1f,width:1.1f}
scoreboard players set P ep_desert_bushes_progress 3
execute if score P ep_desert_bushes_progress matches 6 run function escapemap:ep/desert_bushes/complete
