#######
# Compiled from escapemap/functions/ep/desert_bushes.mcscript
# to .//data/escapemap/functions/ep/desert_bushes/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say complete
function escapemap:ep/desert_bushes/kill
