#######
# Compiled from escapemap/functions/ep/desert_bushes.mcscript
# to .//data/escapemap/functions/ep/desert_bushes/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:ep/desert_bushes/kill
function escapemap:ep/desert_bushes/summon0
scoreboard players set P ep_desert_bushes_progress 0
