#######
# Compiled from escapemap/functions/ep/desert_bushes.mcscript
# to .//data/escapemap/functions/ep/desert_bushes/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=ep_ia_desert_bushes,tag=0] if data entity @s {interaction:{}} run function escapemap:ep/desert_bushes/click_0
execute as @e[tag=ep_ia_desert_bushes,tag=1] if data entity @s {interaction:{}} run function escapemap:ep/desert_bushes/click_1
execute as @e[tag=ep_ia_desert_bushes,tag=2] if data entity @s {interaction:{}} run function escapemap:ep/desert_bushes/click_2
execute as @e[tag=ep_ia_desert_bushes,tag=3] if data entity @s {interaction:{}} run function escapemap:ep/desert_bushes/click_3
execute as @e[tag=ep_ia_desert_bushes,tag=4] if data entity @s {interaction:{}} run function escapemap:ep/desert_bushes/click_4
execute as @e[tag=ep_ia_desert_bushes,tag=5] if data entity @s {interaction:{}} run function escapemap:ep/desert_bushes/click_5
execute if score P ep_desert_bushes_progress matches 0..5 run function escapemap:ep/desert_bushes/particle_0
execute if score P ep_desert_bushes_progress matches 1..5 run function escapemap:ep/desert_bushes/particle_1
execute if score P ep_desert_bushes_progress matches 2..5 run function escapemap:ep/desert_bushes/particle_2
execute if score P ep_desert_bushes_progress matches 3..5 run function escapemap:ep/desert_bushes/particle_3
execute if score P ep_desert_bushes_progress matches 4..5 run function escapemap:ep/desert_bushes/particle_4
execute if score P ep_desert_bushes_progress matches 5..5 run function escapemap:ep/desert_bushes/particle_5
