#######
# Compiled from functions/puzzles/cyan_candle/basement.mcscript
# to .//data/escapemap/functions/puzzles/cyan_candle/basement/cauldron.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P puzzle_basement_complete matches 0 if blocks -113 -41 42 -110 -41 42 -113 -44 42 all run function escapemap:puzzles/cyan_candle/basement/complete

execute if score P puzzle_basement_secret_complete matches 0 if blocks -113 -41 42 -110 -41 42 -113 -46 42 all run function escapemap:puzzles/cyan_candle/basement/secret_complete

