#######
# Compiled from functions/puzzles/cyan_candle/basement.mcscript
# to .//data/escapemap/functions/puzzles/cyan_candle/basement/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set P puzzle_basement_complete 0
scoreboard players set P puzzle_basement_secret_complete 0
fill -113 -41 42 -110 -41 42 minecraft:cauldron
setblock -108 -40 41 waxed_oxidized_copper_bulb[lit=false,powered=false]
setblock -118 -40 41 waxed_copper_bulb[lit=false,powered=false]
setblock -116 -41 46 soul_campfire[lit=false]