#######
# Compiled from functions/puzzles/cyan_candle/basement.mcscript
# to .//data/escapemap/functions/puzzles/cyan_candle/basement/secret_complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/secret_complete {p:"-116 -41 46"}
scoreboard players set P puzzle_basement_secret_complete 1
setblock -118 -40 41 waxed_copper_bulb[lit=true]
