#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/desert_tut.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/desert_tut/click_5.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_desert_tut,tag=5] run data remove entity @s interaction
scoreboard players set P zzz_desert_tut_progress 6
execute if score P zzz_desert_tut_progress matches 6 run function escapemap:zzz/desert_tut/complete
