#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/desert_tut.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/desert_tut/click_0.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_desert_tut,tag=0] run data remove entity @s interaction
kill @e[tag=zzz_ia_desert_tut,tag=1]
kill @e[tag=zzz_ia_desert_tut,tag=2]
kill @e[tag=zzz_ia_desert_tut,tag=3]
kill @e[tag=zzz_ia_desert_tut,tag=4]
kill @e[tag=zzz_ia_desert_tut,tag=5]
summon interaction -150 -47 39 {Tags:["zzz_ia_desert_tut", "1"],height:1.1f,width:1.1f}
scoreboard players set P zzz_desert_tut_progress 1
execute if score P zzz_desert_tut_progress matches 6 run function escapemap:zzz/desert_tut/complete
