#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_026.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.228789f,3.467604f,-0.096174f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.623416f,-0.366992f,0.414197f,0.552367f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.571972f,3.512759f,-0.240435f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.623416f,-0.366992f,0.414197f,0.552367f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
