#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_041.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.226303f,3.484800f,-0.095129f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.642268f,-0.352350f,0.426722f,0.530330f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.565758f,3.555749f,-0.237823f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.642268f,-0.352350f,0.426722f,0.530330f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
