#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_049.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.224528f,3.493882f,-0.094383f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.652005f,-0.344366f,0.433191f,0.518312f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.561320f,3.578456f,-0.235957f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.652005f,-0.344366f,0.433191f,0.518312f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
