#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_015.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.229907f,3.454896f,-0.096644f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.609110f,-0.377447f,0.404692f,0.568104f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.574768f,3.480989f,-0.241610f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.609110f,-0.377447f,0.404692f,0.568104f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
