#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_045.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.225455f,3.489350f,-0.094772f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.647164f,-0.348373f,0.429975f,0.524344f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.563637f,3.567125f,-0.236931f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.647164f,-0.348373f,0.429975f,0.524344f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
