#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_010.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.230217f,3.449102f,-0.096775f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.602476f,-0.382119f,0.400284f,0.575135f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.575544f,3.466506f,-0.241936f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.602476f,-0.382119f,0.400284f,0.575135f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
