#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_048.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.224767f,3.492751f,-0.094483f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.650800f,-0.345370f,0.432390f,0.519824f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.561918f,3.575627f,-0.236208f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.650800f,-0.345370f,0.432390f,0.519824f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
