#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_011.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.230165f,3.450262f,-0.096753f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.603809f,-0.381189f,0.401170f,0.573735f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.575413f,3.469404f,-0.241881f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.603809f,-0.381189f,0.401170f,0.573735f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
