#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_019.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.229570f,3.459524f,-0.096502f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.614359f,-0.373674f,0.408179f,0.562424f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.573924f,3.492559f,-0.241256f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.614359f,-0.373674f,0.408179f,0.562424f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
