#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_031.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.228083f,3.473356f,-0.095877f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.629785f,-0.362160f,0.418428f,0.545095f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.570208f,3.527140f,-0.239693f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.629785f,-0.362160f,0.418428f,0.545095f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
