#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_020.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.229473f,3.460680f,-0.096462f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.615663f,-0.372725f,0.409045f,0.560996f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.573683f,3.495449f,-0.241154f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.615663f,-0.372725f,0.409045f,0.560996f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
