#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_035.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.227430f,3.477944f,-0.095603f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.634819f,-0.358259f,0.421773f,0.539224f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.568575f,3.538610f,-0.239007f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.634819f,-0.358259f,0.421773f,0.539224f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
