#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_014.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.229979f,3.453738f,-0.096674f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.607790f,-0.378386f,0.403815f,0.569516f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.574948f,3.478094f,-0.241686f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.607790f,-0.378386f,0.403815f,0.569516f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
