#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_07_pitch/frame_043.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.225889f,3.487077f,-0.094955f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.644723f,-0.350366f,0.428353f,0.527343f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.564722f,3.561442f,-0.237387f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.644723f,-0.350366f,0.428353f,0.527343f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
