#######
# Compiled from data/escapemap/functions/boatcall.mcscript
# to .//data/escapemap/functions/boatcall/call2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
kill @e[tag=calledBoat]
setblock -115 -41 -39 minecraft:barrier
setblock -115 -43 -39 minecraft:air
setblock -115 -44 -39 minecraft:dark_oak_slab[type=bottom]
setblock -117 -42 -39 barrier
setblock -115 -41 -39 minecraft:air
setblock -115 -43 -39 minecraft:dark_oak_slab[type=bottom]
setblock -115 -44 -39 minecraft:air
setblock -150 -42 124 minecraft:barrier
setblock -150 -44 124 minecraft:spruce_slab[type=bottom]
setblock -150 -43 124 minecraft:air
setblock -154 -42 125 minecraft:barrier
setblock -154 -42 124 minecraft:barrier
setblock -153 -42 123 minecraft:barrier
schedule clear escapemap:boatcall/particle1
schedule clear escapemap:boatcall/particle1_post
schedule clear escapemap:boatcall/summon1
schedule clear escapemap:boatcall/particle2
schedule clear escapemap:boatcall/particle2_post
schedule function escapemap:boatcall/particle2 42t append
schedule function escapemap:boatcall/particle2 60t append
schedule function escapemap:boatcall/particle2 70t append
schedule function escapemap:boatcall/particle2 80t append
schedule function escapemap:boatcall/particle2 90t append
schedule function escapemap:boatcall/particle2 95t append
schedule function escapemap:boatcall/particle2 100t append
schedule function escapemap:boatcall/particle2 105t append
schedule function escapemap:boatcall/particle2 110t append
schedule function escapemap:boatcall/particle2 115t append
schedule function escapemap:boatcall/summon2 120t replace
schedule function escapemap:boatcall/particle2_post 125t append
schedule function escapemap:boatcall/particle2_post 130t append
