#######
# Compiled from data/escapemap/functions/boatcall.mcscript
# to .//data/escapemap/functions/boatcall/particle2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:bubble -118 -43.25 -39 0.7 0 0.7 0.3 75 normal
particle minecraft:snowflake -118 -44.5 -39 0.7 0 0.7 0.1 75 normal
