#######
# Compiled from data/escapemap/functions/boatcall.mcscript
# to .//data/escapemap/functions/boatcall/particle1_post.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:bubble -155 -43 122 0.7 0 0.7 0.3 75 normal
particle minecraft:snowflake -155 -44 122 0.7 0 0.7 0.1 75 normal
