#######
# Compiled from data/escapemap/functions/boatcall.mcscript
# to .//data/escapemap/functions/boatcall/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @a calledBoat 0
setblock -150 -42 124 minecraft:barrier
setblock -150 -44 124 minecraft:spruce_slab[type=bottom]
setblock -150 -43 124 minecraft:air
setblock -115 -41 -39 minecraft:barrier
setblock -115 -43 -39 minecraft:air
setblock -115 -44 -39 minecraft:dark_oak_slab[type=bottom]
kill @e[tag=calledBoat]