#######
# Compiled from functions/puzzles/castle/tutorial.mcscript
# to .//data/escapemap/functions/puzzles/castle/tutorial/cauldron.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if blocks -163 -37 -1 -163 -37 -5 -162 -40 -5 all run function escapemap:puzzles/castle/tutorial/complete
