#######
# Compiled from functions/puzzles/castle/tutorial.mcscript
# to .//data/escapemap/functions/puzzles/castle/tutorial/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P puzzle_castle_tutorial_complete matches 0 run setblock -164 -39 -3 minecraft:redstone_torch
execute if score P puzzle_castle_tutorial_complete matches 0 run function escapemap:puzzles/complete
execute if score P puzzle_castle_tutorial_complete matches 0 run function escapemap:puzzles/castle/onpuzzlecomplete
execute if score P puzzle_castle_tutorial_complete matches 0 run scoreboard players set P puzzle_castle_tutorial_complete 1

