#######
# Compiled from functions/puzzles/castle/tutorial.mcscript
# to .//data/escapemap/functions/puzzles/castle/tutorial/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
fill -163 -37 -1 -163 -37 -5 cauldron
setblock -163 -37 -3 air
clone -125 -48 117 -125 -48 117 -163 -37 -6
scoreboard players set P puzzle_castle_tutorial_complete 0
setblock -164 -39 -3 minecraft:air
setblock -163 -38 -3 minecraft:waxed_oxidized_copper_bulb[lit=false,powered=false]
