#######
# Compiled from puzzles/desert/lights/tutorial2.mcscript
# to .//data/escapemap/functions/puzzles/desert/lights/pp2/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P desert_pp2 matches 0 run function escapemap:puzzles/complete
execute if score P desert_pp2 matches 0 run setblock -148 -45 51 minecraft:waxed_oxidized_copper_bulb[lit=true]
execute if score P desert_pp2 matches 0 run schedule function escapemap:puzzles/desert/lights/pp2/door 5s

scoreboard players set P desert_pp2 1
function escapemap:puzzles/desert/ocd/check
