#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_003.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.230443f,3.440982f,-0.096870f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.593051f,-0.388572f,0.394022f,0.584849f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.576109f,3.446205f,-0.242174f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.593051f,-0.388572f,0.394022f,0.584849f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
