#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_029.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.228380f,3.471057f,-0.096002f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.627248f,-0.364099f,0.416742f,0.548013f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.570950f,3.521393f,-0.240005f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.627248f,-0.364099f,0.416742f,0.548013f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
