#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_008.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.230307f,3.446783f,-0.096812f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.599799f,-0.383973f,0.398506f,0.577926f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.575767f,3.460708f,-0.242030f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.599799f,-0.383973f,0.398506f,0.577926f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
