#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_013.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.230046f,3.452579f,-0.096703f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.606466f,-0.379322f,0.402935f,0.570926f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.575115f,3.475198f,-0.241756f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.606466f,-0.379322f,0.402935f,0.570926f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
