#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_038.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.226889f,3.481376f,-0.095375f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.638559f,-0.355314f,0.424258f,0.534790f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.567222f,3.547190f,-0.238438f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.638559f,-0.355314f,0.424258f,0.534790f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
