#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_024.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.229037f,3.465298f,-0.096278f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.620845f,-0.368911f,0.412489f,0.555256f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.572592f,3.506995f,-0.240695f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.620845f,-0.368911f,0.412489f,0.555256f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
