#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_030.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.228234f,3.472207f,-0.095941f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.628518f,-0.363130f,0.417587f,0.546555f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.570585f,3.524267f,-0.239852f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.628518f,-0.363130f,0.417587f,0.546555f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
