#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_037.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.227074f,3.480233f,-0.095453f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.637316f,-0.356297f,0.423432f,0.536271f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.567685f,3.544332f,-0.238633f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.637316f,-0.356297f,0.423432f,0.536271f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
