#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_025.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.228915f,3.466451f,-0.096227f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.622133f,-0.367953f,0.413344f,0.553813f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.572288f,3.509877f,-0.240568f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.622133f,-0.367953f,0.413344f,0.553813f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
