#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_036.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.227254f,3.479089f,-0.095529f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.636069f,-0.357279f,0.422603f,0.537749f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.568136f,3.541472f,-0.238822f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.636069f,-0.357279f,0.422603f,0.537749f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
