#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_028.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.228521f,3.469907f,-0.096062f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.625974f,-0.365065f,0.415896f,0.549467f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.571303f,3.518516f,-0.240154f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.625974f,-0.365065f,0.415896f,0.549467f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
