#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_021.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.229371f,3.461835f,-0.096419f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.616964f,-0.371775f,0.409910f,0.559566f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.573428f,3.498337f,-0.241047f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.616964f,-0.371775f,0.409910f,0.559566f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
