#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_07_pitch/frame_034.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.227601f,3.476798f,-0.095674f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.633566f,-0.359237f,0.420940f,0.540696f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.569002f,3.535746f,-0.239186f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.633566f,-0.359237f,0.420940f,0.540696f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
