#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_06_yaw/frame_024.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.075010f,3.437500f,-0.238482f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.698915f,-0.107324f,0.107324f,0.698915f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.187525f,3.437500f,-0.596204f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.698915f,-0.107324f,0.107324f,0.698915f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
