#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_06_yaw/frame_114.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.248102f,3.437500f,-0.030749f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.529857f,-0.468243f,0.468243f,0.529857f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.620255f,3.437500f,-0.076872f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.529857f,-0.468243f,0.468243f,0.529857f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
