#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_06_yaw/frame_102.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.240560f,3.437500f,-0.068049f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.563958f,-0.426557f,0.426557f,0.563958f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.601401f,3.437500f,-0.170123f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.563958f,-0.426557f,0.426557f,0.563958f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
