#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_06_yaw/frame_108.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.245042f,3.437500f,-0.049543f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.547305f,-0.447725f,0.447725f,0.547305f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.612605f,3.437500f,-0.123857f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.547305f,-0.447725f,0.447725f,0.547305f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
