#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_06_yaw/frame_022.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.068930f,3.437500f,-0.240309f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.700221f,-0.098441f,0.098441f,0.700221f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.172326f,3.437500f,-0.600774f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.700221f,-0.098441f,0.098441f,0.700221f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
