#######
# Compiled from puzzles/desert/lights/common.mcscript
# to .//data/escapemap/functions/puzzles/desert/lights/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/desert/lights/pp1/reset
function escapemap:puzzles/desert/lights/pp2/reset
function escapemap:puzzles/desert/lights/pp5/reset