#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/finish.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:laser/complete {p:"100,65,100",tag:"laser_01_beam"}