#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/kill.mcfunction
#
# Generated by Minecraft Script for 1.16
######
kill @e[tag=laser_01]
kill @e[tag=laser_01_beam]
