#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/turn_on.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:laser/laser_01/reset
function escapemap:laser/laser_01/step_01_flaps
schedule function escapemap:laser/laser_01/step_02_up 100t
schedule function escapemap:laser/laser_01/step_03_pitch 250t
schedule function escapemap:laser/laser_01/step_04_z_pull 550t
schedule function escapemap:laser/laser_01/step_05_spout_extend 640t
schedule function escapemap:laser/laser_01/step_06_yaw 700t
schedule function escapemap:laser/laser_01/step_07_pitch 830t
schedule function escapemap:laser/laser_01/finish 930t
