#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_06_yaw/frame_119.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247309f,3.437500f,-0.036579f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.535331f,-0.461975f,0.461975f,0.535331f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.618274f,3.437500f,-0.091449f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.535331f,-0.461975f,0.461975f,0.535331f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
