#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_06_yaw/frame_003.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.008973f,3.437500f,-0.249839f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.706993f,-0.012691f,0.012691f,0.706993f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.022431f,3.437500f,-0.624597f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.706993f,-0.012691f,0.012691f,0.706993f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
