#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_06_yaw/frame_080.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.204407f,3.437500f,-0.143937f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.627644f,-0.325673f,0.325673f,0.627644f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.511017f,3.437500f,-0.359842f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.627644f,-0.325673f,0.325673f,0.627644f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
