#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_06_yaw/frame_053.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.148133f,3.437500f,-0.201387f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.671853f,-0.220484f,0.220484f,0.671853f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.370332f,3.437500f,-0.503467f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.671853f,-0.220484f,0.220484f,0.671853f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
