#######
# Compiled from escapemap/functions/super_secrets/common.mcscript
# to .//data/escapemap/functions/super_secrets/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:super_secrets/treetop/trail/load
