#######
# Compiled from escapemap/functions/super_secrets/common.mcscript
# to .//data/escapemap/functions/super_secrets/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:super_secrets/lighthouse/trail/tick
execute positioned -85 -12 -41 run function escapemap:super_secrets/lighthouse/controller/tick
