#######
# Compiled from functions/puzzles/desert/common.mcscript
# to .//data/escapemap/functions/puzzles/desert/leaves_placed.mcfunction
#
# Generated by Minecraft Script for 1.16
######
advancement revoke @s only escapemap:place_leaves
function escapemap:puzzles/desert/ruins/leaves_update
function escapemap:puzzles/desert/depths/leaves_update