#######
# Compiled from functions/puzzles/desert/common.mcscript
# to .//data/escapemap/functions/puzzles/desert/leaves_broken.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @a desert_break 0
function escapemap:puzzles/spawn/leaves_check
function escapemap:puzzles/desert/ruins/leaves_update
function escapemap:puzzles/desert/depths/leaves_update
