#######
# Compiled from functions/puzzles/desert/common.mcscript
# to .//data/escapemap/functions/puzzles/desert/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/desert/faucet_controller/reset
function escapemap:puzzles/desert/shore_door/reset
function escapemap:puzzles/desert/ruins/reset
function escapemap:puzzles/desert/lights/pp1/reset
function escapemap:puzzles/desert/depths/reset
