#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/dark/press.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute store success storage escapemap:tmp isFence byte 1 if block -42 -36 58 dark_oak_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -42 -36 58 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -42 -38 58 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -42 -36 58 air run setblock -42 -36 58 dark_oak_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -42 -38 58 air
execute store success storage escapemap:tmp isFence byte 1 if block -44 -36 59 dark_oak_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -44 -36 59 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -44 -38 59 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -44 -36 59 air run setblock -44 -36 59 dark_oak_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -44 -38 59 air
setblock -47 -36 58 stripped_dark_oak_wood
setblock -47 -34 58 air
schedule function escapemap:puzzles/red_candle/fences/dark/expirestencil 3s replace
