#######
# Compiled from functions/puzzles/radiation/common.mcscript
# to .//data/escapemap/functions/puzzles/radiation/radiation_tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute store result score @s rad_roll run function escapemap:explicit_randomness/roll {range:'1..6'}
attribute @s minecraft:movement_speed modifier remove radiation
execute if score @s rad_tier matches 1.. if score @s rad_roll matches 1 run attribute @s minecraft:movement_speed modifier add radiation -0.01 add_value
execute if score @s rad_tier matches 1.. if score @s rad_roll matches 2 run attribute @s minecraft:movement_speed modifier add radiation -0.02 add_value

execute if score @s rad_tier matches 2.. if score @s rad_roll matches 2 run attribute @s minecraft:movement_speed modifier add radiation -0.03 add_value
execute if score @s rad_tier matches 2.. if score @s rad_roll matches 4 run attribute @s minecraft:movement_speed modifier add radiation -0.04 add_value

execute if score @s rad_tier matches 3.. if score @s rad_roll matches 5 run attribute @s minecraft:movement_speed modifier add radiation -0.05 add_value
execute if score @s rad_tier matches 3.. if score @s rad_roll matches 6 run attribute @s minecraft:movement_speed modifier add radiation -0.06 add_value

