#######
# Compiled from functions/puzzles/radiation/common.mcscript
# to .//data/escapemap/functions/puzzles/radiation/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a if score @s area matches 8 if score @s radiation matches ..999 run scoreboard players add @s radiation 1
execute as @a if score @s area matches 8 if score @s radiation matches ..999 if score @s radiation matches 200 run scoreboard players set @s rad_tier 1
execute as @a if score @s area matches 8 if score @s radiation matches ..999 if score @s radiation matches 200 as @s run function escapemap:puzzles/radiation/apply_effects
execute as @a if score @s area matches 8 if score @s radiation matches ..999 if score @s radiation matches 400 run scoreboard players set @s rad_tier 2
execute as @a if score @s area matches 8 if score @s radiation matches ..999 if score @s radiation matches 400 as @s run function escapemap:puzzles/radiation/apply_effects
execute as @a if score @s area matches 8 if score @s radiation matches ..999 if score @s radiation matches 600 run scoreboard players set @s rad_tier 3
execute as @a if score @s area matches 8 if score @s radiation matches ..999 if score @s radiation matches 600 as @s run function escapemap:puzzles/radiation/apply_effects
execute as @a unless score @s area matches 8 if score @s radiation matches 4.. run scoreboard players remove @s radiation 4
execute as @a unless score @s area matches 8 if score @s radiation matches 4.. if score @s radiation matches 195..199 run scoreboard players set @s rad_tier 0
execute as @a unless score @s area matches 8 if score @s radiation matches 4.. if score @s radiation matches 195..199 as @s run function escapemap:puzzles/radiation/apply_effects
execute as @a unless score @s area matches 8 if score @s radiation matches 4.. if score @s radiation matches 395..399 run scoreboard players set @s rad_tier 1
execute as @a unless score @s area matches 8 if score @s radiation matches 4.. if score @s radiation matches 395..399 as @s run function escapemap:puzzles/radiation/apply_effects
execute as @a unless score @s area matches 8 if score @s radiation matches 4.. if score @s radiation matches 595..599 run scoreboard players set @s rad_tier 2
execute as @a unless score @s area matches 8 if score @s radiation matches 4.. if score @s radiation matches 595..599 as @s run function escapemap:puzzles/radiation/apply_effects
execute as @a unless score @s area matches 8 if score @s radiation matches 1..5 run scoreboard players set @s radiation 0
execute as @a run scoreboard players operation @s rad_div = @s radiation
execute as @a run scoreboard players operation @s rad_div /= 10 numbers
scoreboard players add timer rad_timer 1
execute if score timer rad_timer matches 100 as @a run attribute @s minecraft:movement_speed modifier remove radiation
execute if score timer rad_timer matches 100 as @a[scores={rad_tier=1..}] run function escapemap:puzzles/radiation/radiation_tick
execute if score timer rad_timer matches 100 run scoreboard players set timer rad_timer 0

