#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_yaw/frame_029.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.098485f,3.437500f,-0.229784f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.692664f,-0.142184f,0.142184f,0.692664f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.246214f,3.437500f,-0.574460f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.692664f,-0.142184f,0.142184f,0.692664f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
