#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_yaw/frame_002.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.006980f,3.437500f,-0.249903f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.707038f,-0.009873f,0.009873f,0.707038f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.017451f,3.437500f,-0.624756f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.707038f,-0.009873f,0.009873f,0.707038f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
