#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_yaw/frame_025.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.085505f,3.437500f,-0.234923f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.696364f,-0.122788f,0.122788f,0.696364f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.213763f,3.437500f,-0.587308f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.696364f,-0.122788f,0.122788f,0.696364f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
