#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_yaw/frame_030.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.101684f,3.437500f,-0.228386f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.691655f,-0.147016f,0.147016f,0.691655f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.254210f,3.437500f,-0.570966f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.691655f,-0.147016f,0.147016f,0.691655f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
