#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_06_yaw/frame_038.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.126508f,3.437500f,-0.215628f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.682370f,-0.185396f,0.185396f,0.682370f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.316271f,3.437500f,-0.539071f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.682370f,-0.185396f,0.185396f,0.682370f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
