#######
# Compiled from puzzles/desert/depths/common.mcscript
# to .//data/escapemap/functions/puzzles/desert/depths/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -177 -49 52 lever[powered=false,face=floor]
setblock -169 -51 46 air
setblock -169 -50 50 air
setblock -169 -49 54 air
function escapemap:puzzles/desert/depths/leaves_update
function escapemap:puzzles/desert/depths/pp3/reset
function escapemap:puzzles/desert/depths/pp4/reset