#######
# Compiled from data/escapemap/functions/zzz.mcscript
# to .//data/escapemap/functions/../../../../zzz/test/kill.mcfunction
#
# Generated by Minecraft Script for 1.16
######
kill @e[tag=zzz_ia_test]
