#######
# Compiled from data/escapemap/functions/zzz.mcscript
# to .//data/escapemap/functions/../../../../zzz/test/particle_2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:dust{color:[1,1,1],scale:1} -165,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -164,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -164,5 -6,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -164,5 -5,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -164,5 -5,5 276,0 0.5 0.5 0 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -164,5 -5,5 277,0 0.5 0.5 0 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -164,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -163,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -163,5 -6,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -163,5 -5,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -163,5 -5,5 276,0 0.5 0.5 0 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -163,5 -5,5 277,0 0.5 0.5 0 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -163,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -162,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -162,5 -6,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -162,5 -5,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -162,5 -5,5 276,0 0.5 0.5 0 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -162,5 -5,5 277,0 0.5 0.5 0 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -162,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -161,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -161,5 -6,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -161,5 -5,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -161,5 -5,5 276,0 0.5 0.5 0 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -161,5 -5,5 277,0 0.5 0.5 0 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -161,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -160,0 -5,5 276,5 0 0.5 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -160,5 -6,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -160,5 -5,0 276,5 0.5 0 0.5 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -160,5 -5,5 276,0 0.5 0.5 0 0 4
particle minecraft:dust{color:[1,1,1],scale:1} -160,5 -5,5 277,0 0.5 0.5 0 0 4
