#######
# Compiled from data/escapemap/functions/zzz.mcscript
# to .//data/escapemap/functions/../../../../zzz/test/summon0.mcfunction
#
# Generated by Minecraft Script for 1.16
######
summon interaction -165 -6 272 {Tags:["zzz_ia_test", "0"],height:1.1f,width:1.1f}
