#######
# Compiled from data/escapemap/functions/zzz.mcscript
# to .//data/escapemap/functions/../../../../zzz/test/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_test,tag=0] if data entity @s {interaction:{}} run function escapemap:zzz/test/click_0
execute as @e[tag=zzz_ia_test,tag=1] if data entity @s {interaction:{}} run function escapemap:zzz/test/click_1
execute as @e[tag=zzz_ia_test,tag=2] if data entity @s {interaction:{}} run function escapemap:zzz/test/click_2
execute as @e[tag=zzz_ia_test,tag=3] if data entity @s {interaction:{}} run function escapemap:zzz/test/click_3
execute as @e[tag=zzz_ia_test,tag=4] if data entity @s {interaction:{}} run function escapemap:zzz/test/click_4
execute as @e[tag=zzz_ia_test,tag=5] if data entity @s {interaction:{}} run function escapemap:zzz/test/click_5
execute if score P zzz_test_progress matches 0..5 run function escapemap:zzz/test/particle_0
execute if score P zzz_test_progress matches 1..5 run function escapemap:zzz/test/particle_1
execute if score P zzz_test_progress matches 2..5 run function escapemap:zzz/test/particle_2
execute if score P zzz_test_progress matches 3..5 run function escapemap:zzz/test/particle_3
execute if score P zzz_test_progress matches 4..5 run function escapemap:zzz/test/particle_4
execute if score P zzz_test_progress matches 5..5 run function escapemap:zzz/test/particle_5
