#######
# Compiled from functions/puzzles/castle/smith.mcscript
# to .//data/escapemap/functions/puzzles/castle/smith/cauldron.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say hi
execute if blocks -170 -37 -26 -173 -37 -24 -172 -40 -20 all run say correct
execute if blocks -170 -37 -26 -173 -37 -24 -172 -40 -20 all run function escapemap:puzzles/castle/smith/complete
