#######
# Compiled from functions/puzzles/castle/smith.mcscript
# to .//data/escapemap/functions/puzzles/castle/smith/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P puzzle_castle_smith_complete matches 0 run setblock -173 -37 -24 minecraft:waxed_oxidized_copper_bulb[lit=true]
execute if score P puzzle_castle_smith_complete matches 0 run function escapemap:puzzles/complete
execute if score P puzzle_castle_smith_complete matches 0 run function escapemap:puzzles/castle/onpuzzlecomplete
execute if score P puzzle_castle_smith_complete matches 0 run scoreboard players set P puzzle_castle_smith_complete 1

