#######
# Compiled from functions/puzzles/castle/smith.mcscript
# to .//data/escapemap/functions/puzzles/castle/smith/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
fill -170 -37 -26 -170 -37 -25 cauldron
fill -171 -37 -24 -172 -37 -24 cauldron
fill -173 -37 -25 -173 -37 -26 cauldron
scoreboard players set P puzzle_castle_smith_complete 0
setblock -173 -37 -24 minecraft:waxed_oxidized_copper_bulb[lit=false,powered=false]
