#######
# Compiled from data/escapemap/functions/load.mcscript
# to .//data/escapemap/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard objectives add area dummy
scoreboard objectives add old_area dummy

# Extended from escapemap/functions/puzzles/common.mcscript
# to data/escapemap/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add puzzles_complete dummy
scoreboard objectives add secrets_complete dummy
scoreboard objectives add super_secrets_complete dummy

# Extended from data/escapemap/functions/placements.mcscript
# to data/escapemap/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add place0 dummy

# Extended from escapemap/functions/puzzles/spawn.mcscript
# to data/escapemap/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add spawn_secret dummy

# Extended from data/escapemap/functions/spyglass.mcscript
# to data/escapemap/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add spyglass_ticks dummy
scoreboard objectives add spyglass_using dummy
scoreboard objectives add spyglass_objective dummy

# Extended from functions/super_secrets/lighthouse/controller.mcscript
# to data/escapemap/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add ep_raycast dummy
scoreboard objectives add ep_active dummy
scoreboard objectives add ep_flash_timer dummy
