#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/birch/expireblock.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -41 -36 62 birch_wood