#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/birch/press.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -41 -36 62 air
setblock -41 -38 62 barrier
schedule function escapemap:puzzles/red_candle/fences/birch/expireblock 3s replace
