#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_01_flaps/frame_116.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,3.447839f,-1.739741f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.949836f,0.000000f,0.000000f,0.312749f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,3.447839f,1.739741f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.949836f,0.000000f,0.000000f,0.312749f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
