#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/desert/step_01_flaps/frame_012.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,0.416428f,0.320404f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.129228f,0.000000f,0.000000f,0.991615f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,0.416428f,-0.320404f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.129228f,0.000000f,0.000000f,0.991615f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
