#######
# Compiled from .//functions/output_castle.mcscript
# to .//functions/elevator/cleanup.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set #running escapemap_castle_elevator 0
function escapemap:puzzles/castle/layer2/elevators/elevator/despawn_entities