#######
# Compiled from .//functions/output_desert.mcscript
# to .//functions/elevator/finish_a.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #dir_sign escapemap_desert_elevator matches 1 as @e[type=minecraft:shulker,tag=escapemap_desert_elevator_b] at @s run tp @s ~ ~2 ~
execute if score #dir_sign escapemap_desert_elevator matches -1 as @e[type=minecraft:shulker,tag=escapemap_desert_elevator_a] at @s run tp @s ~ ~-2 ~
execute as @e[type=minecraft:shulker,tag=escapemap_desert_elevator_a,limit=1] at @s run function escapemap:puzzles/desert/elevator/nudge_players
execute if score #dir_sign escapemap_desert_elevator matches 1 as @e[type=minecraft:shulker,tag=escapemap_desert_elevator_a] run data merge entity @s {Peek:0b,AttachFace:0b}
execute if score #dir_sign escapemap_desert_elevator matches -1 as @e[type=minecraft:shulker,tag=escapemap_desert_elevator_a] run data merge entity @s {Peek:100b,AttachFace:0b}
scoreboard players set #a escapemap_desert_elevator 0
scoreboard players set #active escapemap_desert_elevator 1
scoreboard players add #cycle escapemap_desert_elevator 1
execute if score #cycle escapemap_desert_elevator >= #max_cycles escapemap_desert_elevator run function escapemap:puzzles/desert/elevator/arrive
layer2/elevators/elevator/arrive
