#######
# Compiled from .//functions/output_castle.mcscript
# to .//functions/elevator/force_attach_face.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:shulker,tag=escapemap_castle_elevator] run data merge entity @s {AttachFace:0b}
