#######
# Compiled from .//functions/output_desert.mcscript
# to .//functions/elevator/go_to_top.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #running escapemap_desert_elevator matches 0 unless score #current_station escapemap_desert_elevator matches 1 run scoreboard players set #target_station escapemap_desert_elevator 1
execute if score #running escapemap_desert_elevator matches 0 unless score #current_station escapemap_desert_elevator matches 1 run function escapemap:puzzles/desert/elevator/prepare_trip
