#######
# Compiled from .//functions/output2.mcscript
# to .//functions/elevator/go_to_middle.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #running escapemap_nexus_lift matches 0 unless score #current_station escapemap_nexus_lift matches 1 run scoreboard players set #target_station escapemap_nexus_lift 1
execute if score #running escapemap_nexus_lift matches 0 unless score #current_station escapemap_nexus_lift matches 1 run function escapemap:mechanical/elevators/elevator/prepare_trip
