#######
# Compiled from .//functions/output_castle.mcscript
# to .//functions/elevator/go_to_floor1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #running escapemap_castle_elevator matches 0 unless score #current_station escapemap_castle_elevator matches 0 run scoreboard players set #target_station escapemap_castle_elevator 0
execute if score #running escapemap_castle_elevator matches 0 unless score #current_station escapemap_castle_elevator matches 0 run function escapemap:puzzles/castle/layer2/elevators/elevator/prepare_trip
