#######
# Compiled from .//functions/output_desert.mcscript
# to .//functions/elevator/go_to_bottom.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #running escapemap_desert_elevator matches 0 unless score #current_station escapemap_desert_elevator matches 0 run scoreboard players set #target_station escapemap_desert_elevator 0
execute if score #running escapemap_desert_elevator matches 0 unless score #current_station escapemap_desert_elevator matches 0 run function escapemap:puzzles/desert/elevator/prepare_trip
