#######
# Compiled from .//functions/output_desert.mcscript
# to .//functions/elevator/place_station_0_blocks.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -169 -51 -31 minecraft:polished_andesite
setblock -169 -51 -32 minecraft:polished_andesite
setblock -169 -51 -33 minecraft:polished_andesite
setblock -169 -51 -30 minecraft:polished_andesite
setblock -169 -51 -29 minecraft:polished_andesite
setblock -168 -51 -31 minecraft:polished_andesite
setblock -168 -51 -32 minecraft:polished_andesite
setblock -168 -51 -33 minecraft:polished_andesite
setblock -168 -51 -30 minecraft:polished_andesite
setblock -168 -51 -29 minecraft:polished_andesite
setblock -170 -51 -31 minecraft:polished_andesite
setblock -170 -51 -32 minecraft:polished_andesite
setblock -170 -51 -33 minecraft:polished_andesite
setblock -170 -51 -30 minecraft:polished_andesite
setblock -170 -51 -29 minecraft:polished_andesite
setblock -171 -51 -32 minecraft:polished_andesite
setblock -171 -51 -33 minecraft:polished_andesite
setblock -171 -51 -30 minecraft:polished_andesite
setblock -167 -51 -32 minecraft:polished_andesite
setblock -167 -51 -33 minecraft:polished_andesite
setblock -167 -51 -30 minecraft:polished_andesite
setblock -168 -50 -30 minecraft:deepslate_tile_wall
setblock -168 -49 -30 minecraft:deepslate_tile_wall
setblock -168 -48 -30 minecraft:deepslate_tile_wall
setblock -170 -50 -30 minecraft:deepslate_tile_wall
setblock -170 -49 -30 minecraft:deepslate_tile_wall
setblock -170 -48 -30 minecraft:deepslate_tile_wall
setblock -170 -50 -32 minecraft:deepslate_tile_wall
setblock -170 -49 -32 minecraft:deepslate_tile_wall
setblock -170 -48 -32 minecraft:deepslate_tile_wall
setblock -168 -50 -32 minecraft:deepslate_tile_wall
setblock -168 -49 -32 minecraft:deepslate_tile_wall
setblock -168 -48 -32 minecraft:deepslate_tile_wall
setblock -169 -50 -30 minecraft:iron_bars
setblock -169 -49 -30 minecraft:iron_bars
setblock -169 -48 -30 minecraft:deepslate_tile_wall
setblock -169 -50 -32 minecraft:iron_bars
setblock -169 -49 -32 minecraft:iron_bars
setblock -169 -48 -32 minecraft:deepslate_tile_wall
setblock -168 -50 -31 minecraft:iron_bars
setblock -168 -49 -31 minecraft:iron_bars
setblock -168 -48 -31 minecraft:deepslate_tile_wall
setblock -170 -50 -31 minecraft:iron_bars
setblock -170 -49 -31 minecraft:iron_bars
setblock -170 -48 -31 minecraft:deepslate_tile_wall

setblock -167 -45 -45 minecraft:deepslate_bricks
setblock -160 -45 -40 minecraft:deepslate_bricks
setblock -161 -45 -40 minecraft:deepslate_bricks
setblock -162 -45 -40 minecraft:deepslate_bricks
setblock -164 -45 -40 minecraft:deepslate_bricks
setblock -165 -45 -40 minecraft:deepslate_bricks
setblock -166 -45 -40 minecraft:deepslate_bricks
setblock -160 -45 -46 minecraft:deepslate_bricks
setblock -161 -45 -46 minecraft:deepslate_bricks
setblock -162 -45 -46 minecraft:deepslate_bricks
setblock -164 -45 -46 minecraft:deepslate_bricks
setblock -165 -45 -46 minecraft:deepslate_bricks
setblock -166 -45 -46 minecraft:deepslate_bricks
setblock -161 -45 -39 minecraft:deepslate_bricks
setblock -162 -45 -39 minecraft:deepslate_bricks
setblock -164 -45 -39 minecraft:deepslate_bricks
setblock -165 -45 -39 minecraft:deepslate_bricks
setblock -161 -45 -47 minecraft:deepslate_bricks
setblock -162 -45 -47 minecraft:deepslate_bricks
setblock -164 -45 -47 minecraft:deepslate_bricks
setblock -165 -45 -47 minecraft:deepslate_bricks
