#######
# Compiled from .//functions/output2.mcscript
# to .//functions/elevator/prep_down_step_b.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:shulker,tag=escapemap_nexus_lift_b] at @s run tp @s ~ ~1 ~
scoreboard players set #b escapemap_nexus_lift 0
