#######
# Compiled from .//functions/output2.mcscript
# to .//functions/elevator/prep_down_step_a.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:shulker,tag=escapemap_nexus_lift_a] at @s run tp @s ~ ~1 ~
scoreboard players set #a escapemap_nexus_lift 0
