#######
# Compiled from .//functions/output_desert.mcscript
# to .//functions/elevator/stop.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set #running escapemap_desert_elevator 0
execute as @e[type=minecraft:shulker,tag=escapemap_desert_elevator] run data merge entity @s {Peek:0b,AttachFace:0b}
kill @e[type=minecraft:shulker,tag=escapemap_desert_elevator]
kill @e[type=minecraft:block_display,tag=escapemap_desert_elevator_display]
