#######
# Compiled from .//functions/output_desert.mcscript
# to .//functions/elevator/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #running escapemap_desert_elevator matches 1 run function escapemap:puzzles/desert/elevator/force_attach_face
scoreboard players set #do_step escapemap_desert_elevator 0
execute if score #running escapemap_desert_elevator matches 1 run scoreboard players add #tick escapemap_desert_elevator 1
execute if score #running escapemap_desert_elevator matches 1 if score #tick escapemap_desert_elevator >= #tick_divisor escapemap_desert_elevator run scoreboard players set #do_step escapemap_desert_elevator 1
execute if score #do_step escapemap_desert_elevator matches 1 run scoreboard players set #tick escapemap_desert_elevator 0
execute if score #do_step escapemap_desert_elevator matches 1 if score #active escapemap_desert_elevator matches 0 run function escapemap:puzzles/desert/elevator/step_a
execute if score #do_step escapemap_desert_elevator matches 1 if score #active escapemap_desert_elevator matches 1 run function escapemap:puzzles/desert/elevator/step_b
p:puzzles/castle/layer2/elevators/elevator/step_b
