#######
# Compiled from /functions/output/trail.mcscript
# to .//functions/output/trail/kill.mcfunction
#
# Generated by Minecraft Script for 1.16
######
kill @e[tag=ss_trail_lighthouse]
kill @e[tag=ss_trail_lighthouse_end]
