#######
# Compiled from puzzles/castle/tower/ontopofroof.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/ontopofroof/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set P castle_tower_top_complete 1
function escapemap:laser/castle/turn_on
