#######
# Compiled from puzzles/castle/tower/ontopofroof.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/ontopofroof/onitemframe.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P castle_tower_top_complete matches 0 run function escapemap:puzzles/castle/tower/ontopofroof/check
