#######
# Compiled from puzzles/castle/tower/ontopofroof.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/ontopofroof/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set P castle_tower_top_complete 0
data merge entity @e[limit=1,tag=castle_tower_top_frames,tag=frame1] {ItemRotation:5b}
data merge entity @e[limit=1,tag=castle_tower_top_frames,tag=frame2] {ItemRotation:2b}
data merge entity @e[limit=1,tag=castle_tower_top_frames,tag=frame3] {ItemRotation:7b}
data merge entity @e[limit=1,tag=castle_tower_top_frames,tag=frame4] {ItemRotation:3b}
function escapemap:laser/castle/reset
