#######
# Compiled from functions/puzzles/castle/towers.mcscript
# to .//data/escapemap/functions/puzzles/castle/towers/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set P puzzle_castle_towers_complete 0
setblock -162 -30 -46 minecraft:waxed_oxidized_copper_bulb[lit=false]
setblock -162 -34 -45 air
kill @e[tag=castle_towers_frame]
summon item_frame -181 -28 -56 {Facing:1b,ItemRotation:2b,Invulnerable:1b,Tags:["castle_towers_frame","frame1"],Item:{id:"minecraft:spectral_arrow",count:1}}
summon item_frame -186 -28 -26 {Facing:1b,ItemRotation:3b,Invulnerable:1b,Tags:["castle_towers_frame","frame2"],Item:{id:"minecraft:spectral_arrow",count:1}}
summon item_frame -179 -28 -4 {Facing:1b,ItemRotation:1b,Invulnerable:1b,Tags:["castle_towers_frame","frame3"],Item:{id:"minecraft:spectral_arrow",count:1}}
summon item_frame -154 -28 2 {Facing:1b,ItemRotation:2b,Invulnerable:1b,Tags:["castle_towers_frame","frame4"],Item:{id:"minecraft:spectral_arrow",count:1}}
summon item_frame -159 -28 -27 {Facing:1b,ItemRotation:0b,Invulnerable:1b,Tags:["castle_towers_frame","frame5"],Item:{id:"minecraft:spectral_arrow",count:1}}
