#######
# Compiled from escapemap/functions/laser/lighthouse.mcscript
# to .//data/escapemap/functions/laser/lighthouse/step_03_pitch/frame_116.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,3.391706f,-0.873801f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.688355f,0.000000f,0.000000f,0.725374f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=lighthouse,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,3.391706f,-0.873801f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.688355f,0.000000f,0.000000f,0.725374f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
