#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_01_flaps/frame_129.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,3.285361f,-2.284980f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.984254f,0.000000f,0.000000f,0.176763f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,3.285361f,2.284980f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.984254f,0.000000f,0.000000f,0.176763f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
