#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_01_flaps/frame_070.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_flap1,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.787880f,0.082134f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[-0.685977f,0.000000f,0.000000f,0.727623f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_flap2,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.787880f,-0.082134f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.685977f,0.000000f,0.000000f,0.727623f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
