#######
# Compiled from functions/mechanical/elevators/elevator.mcscript
# to .//data/escapemap/functions/mechanical/elevators/elevator/force_attach_face.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:shulker,tag=escapemap_castle_elevator] run data merge entity @s {AttachFace:0b}
