#######
# Compiled from functions/mechanical/elevators/elevator.mcscript
# to .//data/escapemap/functions/mechanical/elevators/elevator/go_to_floor2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #running escapemap_castle_elevator matches 0 unless score #current_station escapemap_castle_elevator matches 1 run scoreboard players set #target_station escapemap_castle_elevator 1
execute if score #running escapemap_castle_elevator matches 0 unless score #current_station escapemap_castle_elevator matches 1 run function escapemap:puzzles/castle/layer2/elevators/elevator/prepare_trip
