#######
# Compiled from functions/puzzles/castle/targets.mcscript
# to .//data/escapemap/functions/puzzles/castle/targets/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -165 -38 -27 cauldron
setblock -165 -37 -26 cauldron
fill -165 -38 -25 -165 -38 -21 minecraft:cauldron
scoreboard players set P puzzle_castle_targets_complete 0
setblock -165 -37 -24 minecraft:waxed_oxidized_copper_bulb[lit=false,powered=false]
