# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'ac3bc3f648f1a8e9a8a352ffd7a0c7c48af37f627202432a0271c889b095ffeb'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack