#######
# Compiled from functions/puzzles/castle/farm.mcscript
# to .//data/escapemap/functions/puzzles/castle/farm/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
fill -178 -37 -42 -178 -37 -46 composter
scoreboard players set P puzzle_castle_farm_complete 0
setblock -178 -37 -47 minecraft:waxed_oxidized_copper_bulb[lit=false,powered=false]
