#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_07_pitch/frame_017.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248777f,3.459231f,-0.011732f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.533415f,-0.466386f,0.508852f,0.488899f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.621943f,3.491827f,-0.029330f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.533415f,-0.466386f,0.508852f,0.488899f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
