#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_07_pitch/frame_025.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247680f,3.469410f,-0.011680f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.543314f,-0.455869f,0.518296f,0.477873f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.619200f,3.517276f,-0.029201f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.543314f,-0.455869f,0.518296f,0.477873f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
