#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_07_pitch/frame_018.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248663f,3.460506f,-0.011727f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.534664f,-0.465082f,0.510045f,0.487532f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.621657f,3.495014f,-0.029317f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.534664f,-0.465082f,0.510045f,0.487532f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
