#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_07_pitch/frame_011.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249327f,3.451572f,-0.011758f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.525843f,-0.474146f,0.501629f,0.497033f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.623316f,3.472679f,-0.029395f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.525843f,-0.474146f,0.501629f,0.497033f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
