#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_07_pitch/frame_012.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249251f,3.452849f,-0.011754f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.527114f,-0.472861f,0.502842f,0.495686f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.623128f,3.475873f,-0.029386f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.527114f,-0.472861f,0.502842f,0.495686f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
