#######
# Compiled from escapemap/functions/laser/castle.mcscript
# to .//data/escapemap/functions/laser/castle/step_07_pitch/frame_002.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249709f,3.440060f,-0.011776f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.514254f,-0.485576f,0.490574f,0.509015f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.624273f,3.443899f,-0.029440f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.514254f,-0.485576f,0.490574f,0.509015f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
