#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_03_pitch/frame_048.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.729610f,-0.514312f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.309017f,0.000000f,0.000000f,0.951057f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.729610f,-0.514312f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.309017f,0.000000f,0.000000f,0.951057f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
