#######
# Compiled from escapemap/functions/area/items.mcscript
# to .//data/escapemap/functions/area/items/candle_flint_and_steel.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if items entity @s weapon.mainhand minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s weapon.mainhand escapemap:candle_flint_and_steel

execute if items entity @s weapon.offhand minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s weapon.offhand escapemap:candle_flint_and_steel

execute if items entity @s player.cursor minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.cursor escapemap:candle_flint_and_steel

execute if items entity @s player.crafting.0 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.crafting.0 escapemap:candle_flint_and_steel

execute if items entity @s player.crafting.1 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.crafting.1 escapemap:candle_flint_and_steel

execute if items entity @s player.crafting.2 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.crafting.2 escapemap:candle_flint_and_steel

execute if items entity @s player.crafting.3 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.crafting.3 escapemap:candle_flint_and_steel

execute if items entity @s hotbar.0 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.0 escapemap:candle_flint_and_steel

execute if items entity @s hotbar.1 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.1 escapemap:candle_flint_and_steel

execute if items entity @s hotbar.2 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.2 escapemap:candle_flint_and_steel

execute if items entity @s hotbar.3 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.3 escapemap:candle_flint_and_steel

execute if items entity @s hotbar.4 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.4 escapemap:candle_flint_and_steel

execute if items entity @s hotbar.5 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.5 escapemap:candle_flint_and_steel

execute if items entity @s hotbar.6 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.6 escapemap:candle_flint_and_steel

execute if items entity @s hotbar.7 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.7 escapemap:candle_flint_and_steel

execute if items entity @s hotbar.8 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.8 escapemap:candle_flint_and_steel

execute if items entity @s inventory.0 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.0 escapemap:candle_flint_and_steel

execute if items entity @s inventory.1 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.1 escapemap:candle_flint_and_steel

execute if items entity @s inventory.2 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.2 escapemap:candle_flint_and_steel

execute if items entity @s inventory.3 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.3 escapemap:candle_flint_and_steel

execute if items entity @s inventory.4 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.4 escapemap:candle_flint_and_steel

execute if items entity @s inventory.5 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.5 escapemap:candle_flint_and_steel

execute if items entity @s inventory.6 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.6 escapemap:candle_flint_and_steel

execute if items entity @s inventory.7 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.7 escapemap:candle_flint_and_steel

execute if items entity @s inventory.8 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.8 escapemap:candle_flint_and_steel

execute if items entity @s inventory.9 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.9 escapemap:candle_flint_and_steel

execute if items entity @s inventory.10 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.10 escapemap:candle_flint_and_steel

execute if items entity @s inventory.11 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.11 escapemap:candle_flint_and_steel

execute if items entity @s inventory.12 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.12 escapemap:candle_flint_and_steel

execute if items entity @s inventory.13 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.13 escapemap:candle_flint_and_steel

execute if items entity @s inventory.14 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.14 escapemap:candle_flint_and_steel

execute if items entity @s inventory.15 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.15 escapemap:candle_flint_and_steel

execute if items entity @s inventory.16 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.16 escapemap:candle_flint_and_steel

execute if items entity @s inventory.17 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.17 escapemap:candle_flint_and_steel

execute if items entity @s inventory.18 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.18 escapemap:candle_flint_and_steel

execute if items entity @s inventory.19 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.19 escapemap:candle_flint_and_steel

execute if items entity @s inventory.20 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.20 escapemap:candle_flint_and_steel

execute if items entity @s inventory.21 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.21 escapemap:candle_flint_and_steel

execute if items entity @s inventory.22 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.22 escapemap:candle_flint_and_steel

execute if items entity @s inventory.23 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.23 escapemap:candle_flint_and_steel

execute if items entity @s inventory.24 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.24 escapemap:candle_flint_and_steel

execute if items entity @s inventory.25 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.25 escapemap:candle_flint_and_steel

execute if items entity @s inventory.26 minecraft:flint_and_steel[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.26 escapemap:candle_flint_and_steel

