#######
# Compiled from escapemap/functions/area/items.mcscript
# to .//data/escapemap/functions/area/items/multitool_spawn_tutorial.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if items entity @s weapon.mainhand minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s weapon.mainhand escapemap:multitool/spawn_tutorial

execute if items entity @s weapon.offhand minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s weapon.offhand escapemap:multitool/spawn_tutorial

execute if items entity @s player.cursor minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s player.cursor escapemap:multitool/spawn_tutorial

execute if items entity @s player.crafting.0 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s player.crafting.0 escapemap:multitool/spawn_tutorial

execute if items entity @s player.crafting.1 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s player.crafting.1 escapemap:multitool/spawn_tutorial

execute if items entity @s player.crafting.2 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s player.crafting.2 escapemap:multitool/spawn_tutorial

execute if items entity @s player.crafting.3 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s player.crafting.3 escapemap:multitool/spawn_tutorial

execute if items entity @s hotbar.0 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s hotbar.0 escapemap:multitool/spawn_tutorial

execute if items entity @s hotbar.1 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s hotbar.1 escapemap:multitool/spawn_tutorial

execute if items entity @s hotbar.2 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s hotbar.2 escapemap:multitool/spawn_tutorial

execute if items entity @s hotbar.3 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s hotbar.3 escapemap:multitool/spawn_tutorial

execute if items entity @s hotbar.4 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s hotbar.4 escapemap:multitool/spawn_tutorial

execute if items entity @s hotbar.5 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s hotbar.5 escapemap:multitool/spawn_tutorial

execute if items entity @s hotbar.6 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s hotbar.6 escapemap:multitool/spawn_tutorial

execute if items entity @s hotbar.7 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s hotbar.7 escapemap:multitool/spawn_tutorial

execute if items entity @s hotbar.8 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s hotbar.8 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.0 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.0 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.1 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.1 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.2 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.2 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.3 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.3 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.4 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.4 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.5 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.5 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.6 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.6 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.7 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.7 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.8 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.8 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.9 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.9 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.10 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.10 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.11 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.11 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.12 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.12 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.13 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.13 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.14 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.14 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.15 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.15 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.16 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.16 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.17 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.17 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.18 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.18 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.19 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.19 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.20 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.20 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.21 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.21 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.22 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.22 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.23 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.23 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.24 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.24 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.25 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.25 escapemap:multitool/spawn_tutorial

execute if items entity @s inventory.26 minecraft:shears[minecraft:custom_data~{puzzle:{id:"multitool"}}] run item modify entity @s inventory.26 escapemap:multitool/spawn_tutorial

