#######
# Compiled from escapemap/functions/area/items.mcscript
# to .//data/escapemap/functions/area/items/village_yard_redstone_active.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if items entity @s weapon.mainhand minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s weapon.mainhand escapemap:village_yard_redstone/active

execute if items entity @s weapon.offhand minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s weapon.offhand escapemap:village_yard_redstone/active

execute if items entity @s player.cursor minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s player.cursor escapemap:village_yard_redstone/active

execute if items entity @s player.crafting.0 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s player.crafting.0 escapemap:village_yard_redstone/active

execute if items entity @s player.crafting.1 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s player.crafting.1 escapemap:village_yard_redstone/active

execute if items entity @s player.crafting.2 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s player.crafting.2 escapemap:village_yard_redstone/active

execute if items entity @s player.crafting.3 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s player.crafting.3 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.0 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s hotbar.0 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.1 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s hotbar.1 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.2 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s hotbar.2 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.3 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s hotbar.3 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.4 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s hotbar.4 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.5 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s hotbar.5 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.6 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s hotbar.6 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.7 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s hotbar.7 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.8 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s hotbar.8 escapemap:village_yard_redstone/active

execute if items entity @s inventory.0 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.0 escapemap:village_yard_redstone/active

execute if items entity @s inventory.1 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.1 escapemap:village_yard_redstone/active

execute if items entity @s inventory.2 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.2 escapemap:village_yard_redstone/active

execute if items entity @s inventory.3 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.3 escapemap:village_yard_redstone/active

execute if items entity @s inventory.4 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.4 escapemap:village_yard_redstone/active

execute if items entity @s inventory.5 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.5 escapemap:village_yard_redstone/active

execute if items entity @s inventory.6 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.6 escapemap:village_yard_redstone/active

execute if items entity @s inventory.7 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.7 escapemap:village_yard_redstone/active

execute if items entity @s inventory.8 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.8 escapemap:village_yard_redstone/active

execute if items entity @s inventory.9 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.9 escapemap:village_yard_redstone/active

execute if items entity @s inventory.10 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.10 escapemap:village_yard_redstone/active

execute if items entity @s inventory.11 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.11 escapemap:village_yard_redstone/active

execute if items entity @s inventory.12 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.12 escapemap:village_yard_redstone/active

execute if items entity @s inventory.13 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.13 escapemap:village_yard_redstone/active

execute if items entity @s inventory.14 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.14 escapemap:village_yard_redstone/active

execute if items entity @s inventory.15 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.15 escapemap:village_yard_redstone/active

execute if items entity @s inventory.16 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.16 escapemap:village_yard_redstone/active

execute if items entity @s inventory.17 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.17 escapemap:village_yard_redstone/active

execute if items entity @s inventory.18 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.18 escapemap:village_yard_redstone/active

execute if items entity @s inventory.19 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.19 escapemap:village_yard_redstone/active

execute if items entity @s inventory.20 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.20 escapemap:village_yard_redstone/active

execute if items entity @s inventory.21 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.21 escapemap:village_yard_redstone/active

execute if items entity @s inventory.22 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.22 escapemap:village_yard_redstone/active

execute if items entity @s inventory.23 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.23 escapemap:village_yard_redstone/active

execute if items entity @s inventory.24 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.24 escapemap:village_yard_redstone/active

execute if items entity @s inventory.25 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.25 escapemap:village_yard_redstone/active

execute if items entity @s inventory.26 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"village_yard"}}] run item modify entity @s inventory.26 escapemap:village_yard_redstone/active

execute if items entity @s weapon.mainhand minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s weapon.mainhand escapemap:village_yard_redstone/active

execute if items entity @s weapon.offhand minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s weapon.offhand escapemap:village_yard_redstone/active

execute if items entity @s player.cursor minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.cursor escapemap:village_yard_redstone/active

execute if items entity @s player.crafting.0 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.crafting.0 escapemap:village_yard_redstone/active

execute if items entity @s player.crafting.1 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.crafting.1 escapemap:village_yard_redstone/active

execute if items entity @s player.crafting.2 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.crafting.2 escapemap:village_yard_redstone/active

execute if items entity @s player.crafting.3 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s player.crafting.3 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.0 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.0 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.1 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.1 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.2 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.2 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.3 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.3 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.4 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.4 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.5 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.5 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.6 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.6 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.7 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.7 escapemap:village_yard_redstone/active

execute if items entity @s hotbar.8 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s hotbar.8 escapemap:village_yard_redstone/active

execute if items entity @s inventory.0 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.0 escapemap:village_yard_redstone/active

execute if items entity @s inventory.1 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.1 escapemap:village_yard_redstone/active

execute if items entity @s inventory.2 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.2 escapemap:village_yard_redstone/active

execute if items entity @s inventory.3 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.3 escapemap:village_yard_redstone/active

execute if items entity @s inventory.4 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.4 escapemap:village_yard_redstone/active

execute if items entity @s inventory.5 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.5 escapemap:village_yard_redstone/active

execute if items entity @s inventory.6 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.6 escapemap:village_yard_redstone/active

execute if items entity @s inventory.7 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.7 escapemap:village_yard_redstone/active

execute if items entity @s inventory.8 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.8 escapemap:village_yard_redstone/active

execute if items entity @s inventory.9 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.9 escapemap:village_yard_redstone/active

execute if items entity @s inventory.10 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.10 escapemap:village_yard_redstone/active

execute if items entity @s inventory.11 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.11 escapemap:village_yard_redstone/active

execute if items entity @s inventory.12 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.12 escapemap:village_yard_redstone/active

execute if items entity @s inventory.13 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.13 escapemap:village_yard_redstone/active

execute if items entity @s inventory.14 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.14 escapemap:village_yard_redstone/active

execute if items entity @s inventory.15 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.15 escapemap:village_yard_redstone/active

execute if items entity @s inventory.16 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.16 escapemap:village_yard_redstone/active

execute if items entity @s inventory.17 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.17 escapemap:village_yard_redstone/active

execute if items entity @s inventory.18 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.18 escapemap:village_yard_redstone/active

execute if items entity @s inventory.19 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.19 escapemap:village_yard_redstone/active

execute if items entity @s inventory.20 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.20 escapemap:village_yard_redstone/active

execute if items entity @s inventory.21 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.21 escapemap:village_yard_redstone/active

execute if items entity @s inventory.22 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.22 escapemap:village_yard_redstone/active

execute if items entity @s inventory.23 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.23 escapemap:village_yard_redstone/active

execute if items entity @s inventory.24 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.24 escapemap:village_yard_redstone/active

execute if items entity @s inventory.25 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.25 escapemap:village_yard_redstone/active

execute if items entity @s inventory.26 minecraft:redstone[minecraft:custom_data~{puzzle:{id:"ground"}}] run item modify entity @s inventory.26 escapemap:village_yard_redstone/active

