#######
# Compiled from escapemap/functions/ep/test.mcscript
# to .//data/escapemap/functions/ep/test/click_3.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=ep_ia_test,tag=3] run data remove entity @s interaction
kill @e[tag=ep_ia_test,tag=4]
kill @e[tag=ep_ia_test,tag=5]
summon interaction -163 -6 272 {Tags:["ep_ia_test", "4"],height:1.1f,width:1.1f}
scoreboard players set P ep_test_progress 4
execute if score P ep_test_progress matches 6 run function escapemap:ep/test/complete
