#######
# Compiled from escapemap/functions/ep/test.mcscript
# to .//data/escapemap/functions/ep/test/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:ep/test/kill
function escapemap:ep/test/summon0
scoreboard players set P ep_test_progress 0
