#######
# Compiled from functions/puzzles/red_candle/fences.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/fences/warped/press.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute store success storage escapemap:tmp isFence byte 1 if block -48 -36 63 warped_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -48 -36 63 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -48 -34 63 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -48 -36 63 air run setblock -48 -36 63 warped_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -48 -34 63 air
execute store success storage escapemap:tmp isFence byte 1 if block -47 -36 64 warped_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -47 -36 64 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -47 -34 64 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -47 -36 64 air run setblock -47 -36 64 warped_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -47 -34 64 air
execute store success storage escapemap:tmp isFence byte 1 if block -58 -36 67 warped_fence
execute if data storage escapemap:tmp {isFence:1b} run setblock -58 -36 67 air
execute if data storage escapemap:tmp {isFence:1b} run setblock -58 -38 67 barrier
execute if data storage escapemap:tmp {isFence:0b} if block -58 -36 67 air run setblock -58 -36 67 warped_fence
execute if data storage escapemap:tmp {isFence:0b} run setblock -58 -38 67 air
