#######
# Compiled from puzzles/castle/tower/carpets.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/carpets/check.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P carpets_progress matches 16 run function escapemap:puzzles/castle/tower/carpets/complete
execute if score P carpets_progress matches 16 run scoreboard players set P carpets_progress 22222

