#######
# Compiled from puzzles/castle/tower/carpets.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/carpets/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set P carpets_progress 0
setblock -166 -46 -24 minecraft:waxed_oxidized_copper_bulb[lit=false,powered=false]
setblock -163 -13 -53 minecraft:iron_trapdoor[half=top]
