#######
# Compiled from functions/puzzles/castle/water_arrows.mcscript
# to .//data/escapemap/functions/puzzles/castle/waterarrows/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P puzzle_castle_water_arrows_complete matches 0 run setblock -179 -38 -37 minecraft:waxed_oxidized_copper_bulb[lit=true]
execute if score P puzzle_castle_water_arrows_complete matches 0 run function escapemap:puzzles/complete
execute if score P puzzle_castle_water_arrows_complete matches 0 run function escapemap:puzzles/castle/onpuzzlecomplete
execute if score P puzzle_castle_water_arrows_complete matches 0 run scoreboard players set P puzzle_castle_water_arrows_complete 1

