#######
# Compiled from functions/super_secrets/lighthouse/outline.mcscript
# to .//data/escapemap/functions/super_secrets/lighthouse/outline/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
kill @e[tag=ep_joint]
kill @e[tag=ep_cursor]
summon armor_stand -34 -33 -36 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_0"]}
scoreboard players set @e[tag=ep_joint_0,limit=1] ep_index 0
summon armor_stand -35 -34 -33 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_1"]}
scoreboard players set @e[tag=ep_joint_1,limit=1] ep_index 1
summon armor_stand -36 -35 -31 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_2"]}
scoreboard players set @e[tag=ep_joint_2,limit=1] ep_index 2
summon armor_stand -37 -35 -29 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_3"]}
scoreboard players set @e[tag=ep_joint_3,limit=1] ep_index 3
summon armor_stand -38 -36 -27 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_4"]}
scoreboard players set @e[tag=ep_joint_4,limit=1] ep_index 4
summon armor_stand -40 -37 -26 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_5"]}
scoreboard players set @e[tag=ep_joint_5,limit=1] ep_index 5
summon armor_stand -42 -39 -24 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_6"]}
scoreboard players set @e[tag=ep_joint_6,limit=1] ep_index 6
summon armor_stand -42 -39 -22 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_7"]}
scoreboard players set @e[tag=ep_joint_7,limit=1] ep_index 7
summon armor_stand -42 -39 -20 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_8"]}
scoreboard players set @e[tag=ep_joint_8,limit=1] ep_index 8
summon armor_stand -42 -39 -18 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_9"]}
scoreboard players set @e[tag=ep_joint_9,limit=1] ep_index 9
summon armor_stand -41 -38 -17 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_joint","ep_joint_10"]}
scoreboard players set @e[tag=ep_joint_10,limit=1] ep_index 10
summon armor_stand 0 0 0 {Invisible:1b,Marker:1b,NoGravity:1b,Tags:["ep_cursor"]}
scoreboard players set @e[tag=ep_cursor,limit=1] ep_progress 0
