#######
# Compiled from functions/puzzles/castle/hay4.mcscript
# to .//data/escapemap/functions/puzzles/castle/hay4/cauldron.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if blocks -173 -37 -13 -176 -37 -13 -176 -40 -13 all run function escapemap:puzzles/castle/hay4/complete
