#######
# Compiled from functions/puzzles/castle/hay4.mcscript
# to .//data/escapemap/functions/puzzles/castle/hay4/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P puzzle_castle_hay4_complete matches 0 run setblock -174 -37 -13 minecraft:waxed_oxidized_copper_bulb[lit=true]
execute if score P puzzle_castle_hay4_complete matches 0 run function escapemap:puzzles/complete
execute if score P puzzle_castle_hay4_complete matches 0 run function escapemap:puzzles/castle/onpuzzlecomplete
execute if score P puzzle_castle_hay4_complete matches 0 run scoreboard players set P puzzle_castle_hay4_complete 1

