#######
# Compiled from functions/puzzles/castle/hay4.mcscript
# to .//data/escapemap/functions/puzzles/castle/hay4/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
fill -173 -37 -13 -176 -37 -13 cauldron
scoreboard players set P puzzle_castle_hay4_complete 0
setblock -174 -37 -13 minecraft:waxed_oxidized_copper_bulb[lit=false,powered=false]
