#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/test2.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/test2/click_5.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_test2,tag=5] run data remove entity @s interaction
kill @e[tag=zzz_ia_test2,tag=6]
kill @e[tag=zzz_ia_test2,tag=7]
kill @e[tag=zzz_ia_test2,tag=8]
kill @e[tag=zzz_ia_test2,tag=9]
kill @e[tag=zzz_ia_test2,tag=10]
summon interaction -167 -3 284 {Tags:["zzz_ia_test2", "6"],height:1.1f,width:1.1f}
scoreboard players set P zzz_test2_progress 6
execute if score P zzz_test2_progress matches 11 run function escapemap:zzz/test2/complete
