#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/test2.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/test2/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say complete
function escapemap:zzz/test2/kill
