#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/test2.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/test2/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:zzz/test2/kill
function escapemap:zzz/test2/summon0
scoreboard players set P zzz_test2_progress 0
