#######
# Compiled from escapemap/functions/super_secrets/common.mcscript
# to # Ts so tuff compiler spit out this file..mcfunction
#
# Generated by Minecraft Script for 1.16
######
# This file is spat out by the compiler because its too tuff to error
# at illegal inputs, instead making new random files somehow
