#######
# Compiled from data/escapemap/functions/main.mcscript
# to .//data/escapemap/functions/jumppad.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/escapemap/functions/main.mcscript
execute as @a at @s run execute if block ~ ~ ~ minecraft:yellow_carpet run effect give @s minecraft:levitation 1 11 true