#######
# Compiled from data/escapemap/functions/main.mcscript
# to .//data/escapemap/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:jumppad
function escapemap:spyglass/tick
function escapemap:boatcall/tick
function escapemap:placements/tick
function escapemap:puzzles/tick
function escapemap:super_secrets/tick
function escapemap:drop/tick
execute as @a run function escapemap:area/tick
execute as @a[gamemode=adventure] run attribute @s minecraft:movement_speed modifier remove minecraft:sprinting
execute as @e[type=item] if items entity @s contents *[minecraft:custom_data~{puzzle:{persistent:true}}] run data modify entity @s Age set value -32768s
execute as @e[type=item_frame,tag=single_use] unless data entity @s Item run kill @s
