#######
# Compiled from data/escapemap/functions/restore_jump.mcscript
# to .//data/escapemap/functions/restorejump.mcfunction
#
# Generated by Minecraft Script for 1.16
######
attribute @s minecraft:jump_strength modifier remove escapemap