#######
# Compiled from data/escapemap/functions/rsod.mcscript
# to .//data/escapemap/functions/rsod.mcfunction
#
# Generated by Minecraft Script for 1.16
######
$setblock $(pos) minecraft:jungle_button[facing=$(facing),powered=true]