#######
# Compiled from functions/puzzles/red_candle/cave.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/cave/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/complete
setblock -64 -42 52 air
function escapemap:puzzles/red_candle/elevator/start
