#######
# Compiled from functions/puzzles/red_candle/cave.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/cave/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -65 -42 52 minecraft:waxed_oxidized_copper_bulb[powered=false,lit=false]
setblock -64 -42 52 stone_button[facing=east]
function escapemap:puzzles/red_candle/cave/warped/expirestencil
function escapemap:puzzles/red_candle/cave/warped/expireblock
setblock -43 -45 67 air
setblock -43 -45 64 oak_fence
setblock -58 -45 65 air
setblock -61 -45 67 oak_fence
setblock -62 -43 71 air
setblock -57 -45 74 air
setblock -43 -43 67 barrier
setblock -43 -43 64 air
setblock -58 -43 65 barrier
setblock -49 -45 65 minecraft:mangrove_fence
setblock -51 -45 63 air
setblock -51 -43 63 barrier
setblock -49 -43 65 air
setblock -53 -45 71 air
setblock -56 -45 72 minecraft:warped_fence
setblock -53 -43 71 barrier
setblock -56 -43 72 air
setblock -53 -45 70 minecraft:bamboo_fence
setblock -53 -43 70 air
setblock -63 -43 60 pale_oak_fence
setblock -63 -43 57 pale_oak_fence
setblock -54 -37 53 minecraft:pale_oak_fence
setblock -54 -35 53 air
