#######
# Compiled from functions/puzzles/desert/faucet.mcscript
# to .//data/escapemap/functions/puzzles/desert/faucet/rotate_handle.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=escapemap_faucet_handle,limit=1] at @s run tp @s ~ ~ ~ ~2.0 ~
function escapemap:puzzles/desert/faucet_controller/onrotate
