#######
# Compiled from functions/puzzles/red_candle/elevator.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/elevator/arrive_top.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set #running escapemap_red_candle 0
setblock -64 -38 51 minecraft:smooth_stone
setblock -64 -38 52 minecraft:smooth_stone
setblock -64 -38 53 minecraft:smooth_stone
setblock -63 -38 51 minecraft:smooth_stone
setblock -63 -38 52 minecraft:smooth_stone
setblock -63 -38 53 minecraft:smooth_stone
setblock -62 -38 51 minecraft:smooth_stone
setblock -62 -38 52 minecraft:smooth_stone
setblock -62 -38 53 minecraft:smooth_stone
execute as @a[x=-65,y=-46,z=50,dx=4,dy=12,dz=4] at @s run tp @s ~ ~0.1 ~
function escapemap:puzzles/red_candle/elevator_listener/end
execute as @e[type=minecraft:shulker,tag=escapemap_red_candle] run data merge entity @s {Peek:0b,AttachFace:0b}
function escapemap:puzzles/red_candle/elevator/despawn_entities
