#######
# Compiled from functions/puzzles/red_candle/elevator.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/elevator/finish_b.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:shulker,tag=escapemap_red_candle_a] at @s run tp @s ~ ~2 ~
execute as @e[type=minecraft:shulker,tag=escapemap_red_candle_b,limit=1] at @s run function escapemap:puzzles/red_candle/elevator/nudge_players
execute as @e[type=minecraft:shulker,tag=escapemap_red_candle_b] run data merge entity @s {Peek:0b,AttachFace:0b}
scoreboard players set #b escapemap_red_candle 0
scoreboard players set #active escapemap_red_candle 0
scoreboard players add #cycle escapemap_red_candle 1
execute if score #cycle escapemap_red_candle matches 6.. run function escapemap:puzzles/red_candle/elevator/arrive_top
