#######
# Compiled from functions/puzzles/red_candle/elevator.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/elevator/nudge_players.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a[x=-65,y=-46,z=50,dx=4,dy=12,dz=4] at @s run tp @s ~ ~0.1 ~
