#######
# Compiled from functions/puzzles/red_candle/elevator.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/elevator/start.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set #a escapemap_red_candle 0
scoreboard players set #b escapemap_red_candle 0
scoreboard players set #active escapemap_red_candle 0
scoreboard players set #cycle escapemap_red_candle 0
scoreboard players set #tick escapemap_red_candle 0
scoreboard players set #running escapemap_red_candle 1
function escapemap:puzzles/red_candle/elevator_listener/start
setblock -64 -44 51 minecraft:air
setblock -64 -44 52 minecraft:air
setblock -64 -44 53 minecraft:air
setblock -63 -44 51 minecraft:air
setblock -63 -44 52 minecraft:air
setblock -63 -44 53 minecraft:air
setblock -62 -44 51 minecraft:air
setblock -62 -44 52 minecraft:air
setblock -62 -44 53 minecraft:air
summon minecraft:shulker -64 -44 51 {Tags:["escapemap_red_candle","escapemap_red_candle_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:10b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -64 -44 52 {Tags:["escapemap_red_candle","escapemap_red_candle_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:10b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -64 -44 53 {Tags:["escapemap_red_candle","escapemap_red_candle_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:10b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -63 -44 51 {Tags:["escapemap_red_candle","escapemap_red_candle_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:10b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -63 -44 52 {Tags:["escapemap_red_candle","escapemap_red_candle_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:10b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -63 -44 53 {Tags:["escapemap_red_candle","escapemap_red_candle_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:10b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -62 -44 51 {Tags:["escapemap_red_candle","escapemap_red_candle_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:10b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -62 -44 52 {Tags:["escapemap_red_candle","escapemap_red_candle_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:10b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -62 -44 53 {Tags:["escapemap_red_candle","escapemap_red_candle_a"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:10b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -64 -45 51 {Tags:["escapemap_red_candle","escapemap_red_candle_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:11b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -64 -45 52 {Tags:["escapemap_red_candle","escapemap_red_candle_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:11b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -64 -45 53 {Tags:["escapemap_red_candle","escapemap_red_candle_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:11b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -63 -45 51 {Tags:["escapemap_red_candle","escapemap_red_candle_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:11b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -63 -45 52 {Tags:["escapemap_red_candle","escapemap_red_candle_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:11b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -63 -45 53 {Tags:["escapemap_red_candle","escapemap_red_candle_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:11b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -62 -45 51 {Tags:["escapemap_red_candle","escapemap_red_candle_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:11b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -62 -45 52 {Tags:["escapemap_red_candle","escapemap_red_candle_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:11b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:shulker -62 -45 53 {Tags:["escapemap_red_candle","escapemap_red_candle_b"],NoAI:1b,Silent:1b,Invulnerable:1b,PersistenceRequired:1b,Peek:0b,AttachFace:0b,Color:11b,active_effects:[{id:"minecraft:invisibility",amplifier:0b,duration:2147483647,show_particles:0b}],attributes:[{id:"minecraft:scale",base:1}]}
summon minecraft:block_display -64 -43 51 {Tags:["escapemap_red_candle","escapemap_red_candle_display"],block_state:{Name:"minecraft:smooth_stone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display -64 -43 52 {Tags:["escapemap_red_candle","escapemap_red_candle_display"],block_state:{Name:"minecraft:smooth_stone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display -64 -43 53 {Tags:["escapemap_red_candle","escapemap_red_candle_display"],block_state:{Name:"minecraft:smooth_stone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display -63 -43 51 {Tags:["escapemap_red_candle","escapemap_red_candle_display"],block_state:{Name:"minecraft:smooth_stone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display -63 -43 52 {Tags:["escapemap_red_candle","escapemap_red_candle_display"],block_state:{Name:"minecraft:smooth_stone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display -63 -43 53 {Tags:["escapemap_red_candle","escapemap_red_candle_display"],block_state:{Name:"minecraft:smooth_stone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display -62 -43 51 {Tags:["escapemap_red_candle","escapemap_red_candle_display"],block_state:{Name:"minecraft:smooth_stone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display -62 -43 52 {Tags:["escapemap_red_candle","escapemap_red_candle_display"],block_state:{Name:"minecraft:smooth_stone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
summon minecraft:block_display -62 -43 53 {Tags:["escapemap_red_candle","escapemap_red_candle_display"],block_state:{Name:"minecraft:smooth_stone"},interpolation_duration:1,teleport_duration:1,transformation:{translation:[-0.5f,0f,-0.5f],scale:[1f,0.08f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
execute as @a[x=-65,y=-46,z=50,dx=4,dy=12,dz=4] at @s run tp @s ~ ~0.1 ~
