#######
# Compiled from functions/puzzles/red_candle/elevator.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/elevator/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score #running escapemap_red_candle matches 1 run function escapemap:puzzles/red_candle/elevator/force_attach_face
scoreboard players set #do_step escapemap_red_candle 0
execute if score #running escapemap_red_candle matches 1 run scoreboard players add #tick escapemap_red_candle 1
execute if score #running escapemap_red_candle matches 1 if score #tick escapemap_red_candle >= #tick_divisor escapemap_red_candle run scoreboard players set #do_step escapemap_red_candle 1
execute if score #do_step escapemap_red_candle matches 1 run scoreboard players set #tick escapemap_red_candle 0
execute if score #do_step escapemap_red_candle matches 1 if score #active escapemap_red_candle matches 0 run function escapemap:puzzles/red_candle/elevator/step_a
execute if score #do_step escapemap_red_candle matches 1 if score #active escapemap_red_candle matches 1 run function escapemap:puzzles/red_candle/elevator/step_b
