#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_046.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.152481f,3.516412f,-0.181720f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.762151f,-0.200067f,0.277400f,0.549680f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.381204f,3.634781f,-0.454301f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.762151f,-0.200067f,0.277400f,0.549680f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
