#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_024.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.158447f,3.479192f,-0.188829f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.717733f,-0.220760f,0.261234f,0.606532f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.396116f,3.541730f,-0.472073f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.717733f,-0.220760f,0.261234f,0.606532f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
