#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_032.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.156703f,3.492887f,-0.186752f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.734389f,-0.213379f,0.267296f,0.586255f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.391759f,3.575968f,-0.466880f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.734389f,-0.213379f,0.267296f,0.586255f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
