#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_036.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.155648f,3.499672f,-0.185494f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.742503f,-0.209627f,0.270249f,0.575944f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.389121f,3.592931f,-0.463736f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.742503f,-0.209627f,0.270249f,0.575944f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
