#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_030.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.157185f,3.489478f,-0.187326f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.730278f,-0.215240f,0.265800f,0.591368f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.392963f,3.567445f,-0.468315f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.730278f,-0.215240f,0.265800f,0.591368f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
