#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_034.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.156191f,3.496286f,-0.186141f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.738464f,-0.211508f,0.268779f,0.581114f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.390478f,3.584464f,-0.465353f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.738464f,-0.211508f,0.268779f,0.581114f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
