#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_044.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.153175f,3.513092f,-0.182547f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.758295f,-0.201999f,0.275997f,0.554988f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.382937f,3.626481f,-0.456367f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.758295f,-0.201999f,0.275997f,0.554988f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
