#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_005.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.160599f,3.446225f,-0.191394f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.675958f,-0.237587f,0.246029f,0.652765f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.401498f,3.459312f,-0.478486f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.675958f,-0.237587f,0.246029f,0.652765f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
