#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_016.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.159695f,3.465367f,-0.190318f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.700518f,-0.227968f,0.254968f,0.626336f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.399239f,3.507168f,-0.475794f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.700518f,-0.227968f,0.254968f,0.626336f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
