#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_008.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.160446f,3.451455f,-0.191212f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.682757f,-0.234998f,0.248503f,0.645651f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.401116f,3.472388f,-0.478031f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.682757f,-0.234998f,0.248503f,0.645651f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
