#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_037.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.155366f,3.501361f,-0.185157f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.744509f,-0.208682f,0.270979f,0.573349f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.388414f,3.597154f,-0.462894f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.744509f,-0.208682f,0.270979f,0.573349f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
