#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_023.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.158630f,3.477470f,-0.189048f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.715612f,-0.221670f,0.260461f,0.609033f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.396574f,3.537426f,-0.472619f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.715612f,-0.221670f,0.260461f,0.609033f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
