#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/laser_01/step_07_pitch/frame_028.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.157636f,3.486059f,-0.187864f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.726132f,-0.217091f,0.264290f,0.596452f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=laser_01,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.394091f,3.558896f,-0.469660f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.726132f,-0.217091f,0.264290f,0.596452f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
