#######
# Compiled from functions/puzzles/desert/corridor.mcscript
# to .//data/escapemap/functions/puzzles/desert/corridor/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score P desert_corridor matches 0 run function escapemap:puzzles/complete
execute if score P desert_corridor matches 0 run setblock -172 -51 31 waxed_oxidized_copper_bulb[lit=true]
execute if score P desert_corridor matches 0 run scoreboard players set P desert_corridor 1

