#######
# Compiled from functions/puzzles/desert/corridor.mcscript
# to .//data/escapemap/functions/puzzles/desert/corridor/line1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data modify storage escapemap:tmp isRedstone set value 0b
execute if block -190 -49 48 redstone_block run data modify storage escapemap:tmp isRedstone set value 1b
execute if data storage escapemap:tmp {isRedstone:1b} run setblock -190 -49 48 air
execute if data storage escapemap:tmp {isRedstone:0b} run setblock -190 -49 48 redstone_block
data modify storage escapemap:tmp isRedstone set value 0b
execute if block -184 -49 46 redstone_block run data modify storage escapemap:tmp isRedstone set value 1b
execute if data storage escapemap:tmp {isRedstone:1b} run setblock -184 -49 46 air
execute if data storage escapemap:tmp {isRedstone:0b} run setblock -184 -49 46 redstone_block
data modify storage escapemap:tmp isRedstone set value 0b
execute if block -190 -49 44 redstone_block run data modify storage escapemap:tmp isRedstone set value 1b
execute if data storage escapemap:tmp {isRedstone:1b} run setblock -190 -49 44 air
execute if data storage escapemap:tmp {isRedstone:0b} run setblock -190 -49 44 redstone_block
