#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/castle_tower.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/castle_tower/click_5.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_castle_tower,tag=5] run data remove entity @s interaction
scoreboard players set P zzz_castle_tower_progress 6
execute if score P zzz_castle_tower_progress matches 6 run function escapemap:zzz/castle_tower/complete
