#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/castle_tower.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/castle_tower/click_4.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_castle_tower,tag=4] run data remove entity @s interaction
kill @e[tag=zzz_ia_castle_tower,tag=5]
summon interaction -164 -18 -50 {Tags:["zzz_ia_castle_tower", "5"],height:1.1f,width:1.1f}
scoreboard players set P zzz_castle_tower_progress 5
execute if score P zzz_castle_tower_progress matches 6 run function escapemap:zzz/castle_tower/complete
