#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/castle_tower.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/castle_tower/kill.mcfunction
#
# Generated by Minecraft Script for 1.16
######
kill @e[tag=zzz_ia_castle_tower]
