#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/castle_tower.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/castle_tower/particle_2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -18.1 -46.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -18.1 -46.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -17.6 -46.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -47.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -46.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -18.1 -47.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -18.1 -47.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -17.6 -47.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -48.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -47.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -18.1 -48.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -18.1 -48.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -17.6 -48.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -49.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -48.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -18.1 -49.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -18.1 -49.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -17.6 -49.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -50.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -49.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -18.1 -50.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -18.1 -50.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -17.6 -50.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -51.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -50.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -18.1 -51.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -18.1 -51.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -17.6 -51.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -52.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -51.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -160.0 -18.1 -52.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.0 -18.1 -52.5 0 0.5 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -17.6 -52.5 0.5 0 0.5 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -53.0 0.5 0.5 0 0 1
particle minecraft:dust{color:[1,1,1],scale:1} -159.5 -18.1 -52.0 0.5 0.5 0 0 1
