#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/castle_tower.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/castle_tower/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:zzz/castle_tower/kill
function escapemap:zzz/castle_tower/summon0
scoreboard players set P zzz_castle_tower_progress 0
