#######
# Compiled from seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/castle_tower.mcscript
# to .//data/escapemap/functions/dontlookmax/seriouslyyouwillgetspoiled/whenyoulookatthis/ucantfinditforurself/../../../../zzz/castle_tower/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=zzz_ia_castle_tower,tag=0] if data entity @s {interaction:{}} run function escapemap:zzz/castle_tower/click_0
execute as @e[tag=zzz_ia_castle_tower,tag=1] if data entity @s {interaction:{}} run function escapemap:zzz/castle_tower/click_1
execute as @e[tag=zzz_ia_castle_tower,tag=2] if data entity @s {interaction:{}} run function escapemap:zzz/castle_tower/click_2
execute as @e[tag=zzz_ia_castle_tower,tag=3] if data entity @s {interaction:{}} run function escapemap:zzz/castle_tower/click_3
execute as @e[tag=zzz_ia_castle_tower,tag=4] if data entity @s {interaction:{}} run function escapemap:zzz/castle_tower/click_4
execute as @e[tag=zzz_ia_castle_tower,tag=5] if data entity @s {interaction:{}} run function escapemap:zzz/castle_tower/click_5
execute if score P zzz_castle_tower_progress matches 0..5 run function escapemap:zzz/castle_tower/particle_0
execute if score P zzz_castle_tower_progress matches 1..5 run function escapemap:zzz/castle_tower/particle_1
execute if score P zzz_castle_tower_progress matches 2..5 run function escapemap:zzz/castle_tower/particle_2
execute if score P zzz_castle_tower_progress matches 3..5 run function escapemap:zzz/castle_tower/particle_3
execute if score P zzz_castle_tower_progress matches 4..5 run function escapemap:zzz/castle_tower/particle_4
execute if score P zzz_castle_tower_progress matches 5..5 run function escapemap:zzz/castle_tower/particle_5
