#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_06_yaw/frame_032.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.091642f,3.437500f,-0.232598f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.694693f,-0.131917f,0.131917f,0.694693f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.229104f,3.437500f,-0.581495f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.694693f,-0.131917f,0.131917f,0.694693f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
