#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_06_yaw/frame_098.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.228130f,3.437500f,-0.102258f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.593513f,-0.384372f,0.384372f,0.593513f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.570325f,3.437500f,-0.255645f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.593513f,-0.384372f,0.384372f,0.593513f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
