#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_06_yaw/frame_037.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.105116f,3.437500f,-0.226827f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.690527f,-0.152226f,0.152226f,0.690527f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.262791f,3.437500f,-0.567068f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.690527f,-0.152226f,0.152226f,0.690527f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
