#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_06_yaw/frame_057.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.154958f,3.437500f,-0.196183f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.667970f,-0.231984f,0.231984f,0.667970f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.387396f,3.437500f,-0.490458f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.667970f,-0.231984f,0.231984f,0.667970f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
