#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_06_yaw/frame_045.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.125906f,3.437500f,-0.215981f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.682628f,-0.184443f,0.184443f,0.682628f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.314765f,3.437500f,-0.539952f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.682628f,-0.184443f,0.184443f,0.682628f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
