#######
# Compiled from escapemap/functions/puzzles/common.mcscript
# to .//data/escapemap/functions/puzzles/complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players add @a puzzles_complete 1
