#######
# Compiled from escapemap/functions/puzzles/common.mcscript
# to .//data/escapemap/functions/puzzles/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######



function escapemap:puzzles/spawn/load
function escapemap:puzzles/red_candle/load
