#######
# Compiled from escapemap/functions/puzzles/common.mcscript
# to .//data/escapemap/functions/puzzles/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @a puzzles_complete 0
scoreboard players set @a secrets_complete 0
scoreboard players set @a super_secrets_complete 0
function escapemap:puzzles/white_candle/reset
function escapemap:puzzles/cyan_candle/reset
function escapemap:puzzles/red_candle/reset
function escapemap:puzzles/spawn/reset