#######
# Compiled from escapemap/functions/puzzles/common.mcscript
# to .//data/escapemap/functions/puzzles/secret_complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players add @a secrets_complete 1
