#######
# Compiled from escapemap/functions/puzzles/common.mcscript
# to .//data/escapemap/functions/puzzles/super_secret_complete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players add @a super_secrets_complete 1
