#######
# Compiled from escapemap/functions/puzzles/common.mcscript
# to .//data/escapemap/functions/puzzles/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a[scores={super_secrets_complete=1..}] run title @s actionbar ["",{"score":{"name":"@s","objective":"puzzles_complete"}},{"text":" +"},{"score":{"name":"@s","objective":"secrets_complete"}},{"text":" (+"},{"score":{"name":"@s","objective":"super_secrets_complete"}},{"text":")"}]
execute as @a[scores={super_secrets_complete=0,secrets_complete=1..}] run title @s actionbar ["",{"score":{"name":"@s","objective":"puzzles_complete"}},{"text":" +"},{"score":{"name":"@s","objective":"secrets_complete"}}]
execute as @a[scores={secrets_complete=0}] run title @s actionbar ["",{"score":{"name":"@s","objective":"puzzles_complete"}}]
function escapemap:puzzles/spawn/tick
