#######
# Compiled from functions/super_secrets/treetop/trail.mcscript
# to .//data/escapemap/functions/super_secrets/treetop/trail/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @a treetop_trail 0
