#######
# Compiled from functions/super_secrets/treetop/trail.mcscript
# to .//data/escapemap/functions/super_secrets/treetop/trail/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if score @p treetop_trail matches 1.. run scoreboard players add @a treetop_trail 1

execute if score @p treetop_trail matches 1 at @e[type=minecraft:marker,tag=ss_trail_treetop_0,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 1 at @e[type=minecraft:marker,tag=ss_trail_treetop_1,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 2 at @e[type=minecraft:marker,tag=ss_trail_treetop_2,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 2 at @e[type=minecraft:marker,tag=ss_trail_treetop_3,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 3 at @e[type=minecraft:marker,tag=ss_trail_treetop_4,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 3 at @e[type=minecraft:marker,tag=ss_trail_treetop_5,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 4 at @e[type=minecraft:marker,tag=ss_trail_treetop_6,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 4 at @e[type=minecraft:marker,tag=ss_trail_treetop_7,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 5 at @e[type=minecraft:marker,tag=ss_trail_treetop_8,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 5 at @e[type=minecraft:marker,tag=ss_trail_treetop_9,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 6 at @e[type=minecraft:marker,tag=ss_trail_treetop_10,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 6 at @e[type=minecraft:marker,tag=ss_trail_treetop_11,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 7 at @e[type=minecraft:marker,tag=ss_trail_treetop_12,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 7 at @e[type=minecraft:marker,tag=ss_trail_treetop_13,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 8 at @e[type=minecraft:marker,tag=ss_trail_treetop_14,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 8 at @e[type=minecraft:marker,tag=ss_trail_treetop_15,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 9 at @e[type=minecraft:marker,tag=ss_trail_treetop_16,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 9 at @e[type=minecraft:marker,tag=ss_trail_treetop_17,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 10 at @e[type=minecraft:marker,tag=ss_trail_treetop_18,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 10 at @e[type=minecraft:marker,tag=ss_trail_treetop_19,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 11 at @e[type=minecraft:marker,tag=ss_trail_treetop_20,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 11 at @e[type=minecraft:marker,tag=ss_trail_treetop_21,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 12 at @e[type=minecraft:marker,tag=ss_trail_treetop_22,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 12 at @e[type=minecraft:marker,tag=ss_trail_treetop_23,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 13 at @e[type=minecraft:marker,tag=ss_trail_treetop_24,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 13 at @e[type=minecraft:marker,tag=ss_trail_treetop_25,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 14 at @e[type=minecraft:marker,tag=ss_trail_treetop_26,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 14 at @e[type=minecraft:marker,tag=ss_trail_treetop_27,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 15 at @e[type=minecraft:marker,tag=ss_trail_treetop_28,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 15 at @e[type=minecraft:marker,tag=ss_trail_treetop_29,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 16 at @e[type=minecraft:marker,tag=ss_trail_treetop_30,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 16 at @e[type=minecraft:marker,tag=ss_trail_treetop_31,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 17 at @e[type=minecraft:marker,tag=ss_trail_treetop_32,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 17 at @e[type=minecraft:marker,tag=ss_trail_treetop_33,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 18 at @e[type=minecraft:marker,tag=ss_trail_treetop_34,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 18 at @e[type=minecraft:marker,tag=ss_trail_treetop_35,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 19 at @e[type=minecraft:marker,tag=ss_trail_treetop_36,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 19 at @e[type=minecraft:marker,tag=ss_trail_treetop_37,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 20 at @e[type=minecraft:marker,tag=ss_trail_treetop_38,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 20 at @e[type=minecraft:marker,tag=ss_trail_treetop_39,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 21 at @e[type=minecraft:marker,tag=ss_trail_treetop_40,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 21 at @e[type=minecraft:marker,tag=ss_trail_treetop_41,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 22 at @e[type=minecraft:marker,tag=ss_trail_treetop_42,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 22 at @e[type=minecraft:marker,tag=ss_trail_treetop_43,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 23 at @e[type=minecraft:marker,tag=ss_trail_treetop_44,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 23 at @e[type=minecraft:marker,tag=ss_trail_treetop_45,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 24 at @e[type=minecraft:marker,tag=ss_trail_treetop_46,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 24 at @e[type=minecraft:marker,tag=ss_trail_treetop_47,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 25 at @e[type=minecraft:marker,tag=ss_trail_treetop_48,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 25 at @e[type=minecraft:marker,tag=ss_trail_treetop_49,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 26 at @e[type=minecraft:marker,tag=ss_trail_treetop_50,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 26 at @e[type=minecraft:marker,tag=ss_trail_treetop_51,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 27 at @e[type=minecraft:marker,tag=ss_trail_treetop_52,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 27 at @e[type=minecraft:marker,tag=ss_trail_treetop_53,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 28 at @e[type=minecraft:marker,tag=ss_trail_treetop_54,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 28 at @e[type=minecraft:marker,tag=ss_trail_treetop_55,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 29 at @e[type=minecraft:marker,tag=ss_trail_treetop_56,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 29 at @e[type=minecraft:marker,tag=ss_trail_treetop_57,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 30 at @e[type=minecraft:marker,tag=ss_trail_treetop_58,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 30 at @e[type=minecraft:marker,tag=ss_trail_treetop_59,limit=1] run function escapemap:super_secrets/particles/head
execute if score @p treetop_trail matches 31..33 at @e[type=minecraft:marker,tag=ss_trail_treetop_end,limit=1] run function escapemap:super_secrets/particles/end
execute if score @p treetop_trail matches 33.. at @e[type=minecraft:marker,tag=ss_trail_treetop_end,limit=1] run function escapemap:super_secrets/treetop/trail/end
