#######
# Compiled from puzzles/castle/tower/common.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/castle/tower/carpets/load
function escapemap:puzzles/castle/tower/lecterns/load
