#######
# Compiled from puzzles/castle/tower/common.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/castle/tower/carpets/reset
function escapemap:puzzles/castle/tower/lecterns/reset
function escapemap:puzzles/castle/tower/door/reset
function escapemap:puzzles/castle/tower/ontopofroof/reset
