#######
# Compiled from puzzles/castle/tower/common.mcscript
# to .//data/escapemap/functions/puzzles/castle/tower/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function escapemap:puzzles/castle/tower/lecterns/tick