#######
# Compiled from functions/puzzles/castle/pottery.mcscript
# to .//data/escapemap/functions/puzzles/castle/pottery/reset.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set P puzzle_castle_pottery_complete 0
setblock -167 -39 -52 air
setblock -164 -37 -51 minecraft:waxed_oxidized_copper_bulb[lit=false]
kill @e[tag=castle_pottery_frame]
summon item_frame -163 -36 -53 {Facing:3b,Invulnerable:1b,Tags:["castle_pottery_frame","frame4"],Item:{id:"minecraft:flow_pottery_sherd",count:1}}
summon item_frame -164 -36 -53 {Facing:3b,Invulnerable:1b,Tags:["castle_pottery_frame","frame3"],Item:{id:"minecraft:flow_pottery_sherd",count:1}}
summon item_frame -165 -36 -53 {Facing:3b,Invulnerable:1b,Tags:["castle_pottery_frame","frame2"],Item:{id:"minecraft:flow_pottery_sherd",count:1}}
summon item_frame -166 -36 -53 {Facing:3b,Invulnerable:1b,Tags:["castle_pottery_frame","frame1"],Item:{id:"minecraft:flow_pottery_sherd",count:1}}
