#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_057.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247772f,3.468685f,-0.011685f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.542615f,-0.456626f,0.517628f,0.478668f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.619430f,3.515462f,-0.029212f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.542615f,-0.456626f,0.517628f,0.478668f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
