#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_065.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247187f,3.473034f,-0.011657f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.546795f,-0.452066f,0.521616f,0.473887f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.617968f,3.526335f,-0.029143f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.546795f,-0.452066f,0.521616f,0.473887f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
