#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_037.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248900f,3.457773f,-0.011738f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.531982f,-0.467873f,0.507486f,0.490457f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.622250f,3.488183f,-0.029345f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.531982f,-0.467873f,0.507486f,0.490457f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
