#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_043.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248612f,3.461052f,-0.011724f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.535199f,-0.464522f,0.510554f,0.486945f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.621530f,3.496380f,-0.029311f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.535199f,-0.464522f,0.510554f,0.486945f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
