#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_013.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249170f,3.454127f,-0.011751f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.528381f,-0.471572f,0.504050f,0.494335f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.622924f,3.479066f,-0.029376f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.528381f,-0.471572f,0.504050f,0.494335f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
