#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_021.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248281f,3.464326f,-0.011709f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.538393f,-0.461152f,0.513601f,0.483411f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.620702f,3.504566f,-0.029272f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.538393f,-0.461152f,0.513601f,0.483411f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
