#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_040.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248761f,3.459413f,-0.011731f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.533593f,-0.466200f,0.509023f,0.488704f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.621903f,3.492283f,-0.029328f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.533593f,-0.466200f,0.509023f,0.488704f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
