#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_008.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249513f,3.447736f,-0.011767f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.522011f,-0.477985f,0.497973f,0.501057f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.623783f,3.463091f,-0.029417f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.522011f,-0.477985f,0.497973f,0.501057f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
