#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_063.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247340f,3.471948f,-0.011664f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.545754f,-0.453209f,0.520623f,0.475086f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.618351f,3.523619f,-0.029161f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.545754f,-0.453209f,0.520623f,0.475086f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
