#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_004.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249670f,3.442619f,-0.011774f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.516853f,-0.483058f,0.493053f,0.506376f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.624175f,3.450298f,-0.029435f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.516853f,-0.483058f,0.493053f,0.506376f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
