#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_047.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248396f,3.463235f,-0.011714f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.537331f,-0.462277f,0.512588f,0.484592f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.620990f,3.501838f,-0.029285f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.537331f,-0.462277f,0.512588f,0.484592f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
