#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_024.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247840f,3.468141f,-0.011688f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.542089f,-0.457194f,0.517127f,0.479263f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.619599f,3.514101f,-0.029220f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.542089f,-0.457194f,0.517127f,0.479263f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
