#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_028.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247161f,3.473215f,-0.011656f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.546968f,-0.451875f,0.521781f,0.473687f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.617903f,3.526787f,-0.029140f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.546968f,-0.451875f,0.521781f,0.473687f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
