#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_058.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247703f,3.469229f,-0.011681f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.543139f,-0.456058f,0.518129f,0.478072f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.619258f,3.516823f,-0.029203f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.543139f,-0.456058f,0.518129f,0.478072f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
