#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_054.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.247972f,3.467051f,-0.011694f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.541036f,-0.458327f,0.516123f,0.480451f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.619929f,3.511379f,-0.029235f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.541036f,-0.458327f,0.516123f,0.480451f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
