#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_069.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.246866f,3.475204f,-0.011642f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.548869f,-0.449772f,0.523595f,0.471483f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.617165f,3.531761f,-0.029105f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.548869f,-0.449772f,0.523595f,0.471483f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
