#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_001.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249719f,3.438780f,-0.011776f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.512949f,-0.486830f,0.489329f,0.510330f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.624298f,3.440700f,-0.029441f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.512949f,-0.486830f,0.489329f,0.510330f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
