#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_050.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248221f,3.464872f,-0.011706f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.538923f,-0.460588f,0.514107f,0.482820f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.620553f,3.505929f,-0.029265f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.538923f,-0.460588f,0.514107f,0.482820f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
