#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_053.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.248036f,3.466507f,-0.011697f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.540509f,-0.458893f,0.515620f,0.481044f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.620090f,3.510017f,-0.029243f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.540509f,-0.458893f,0.515620f,0.481044f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
