#######
# Compiled from /functions/output/generated_lasers.mcscript
# to .//functions/output/castle/step_07_pitch/frame_034.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.249028f,3.456133f,-0.011744f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.530365f,-0.469541f,0.505943f,0.492205f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=castle,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:2,transformation:{translation:[0.622570f,3.484082f,-0.029360f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.530365f,-0.469541f,0.505943f,0.492205f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
