#######
# Compiled from functions/puzzles/red_candle/elevator_listener.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/elevator_listener/end.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -63 -42 54 air
setblock -63 -43 54 air
setblock -63 -42 53 barrier
fill -65 -36 50 -61 -36 54 air replace barrier
