#######
# Compiled from functions/puzzles/red_candle/elevator_listener.mcscript
# to .//data/escapemap/functions/puzzles/red_candle/elevator_listener/start.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -63 -42 54 barrier
setblock -63 -43 54 barrier
