#######
# Compiled from functions/puzzles/radiation/lab.mcscript
# to .//data/escapemap/functions/puzzles/radiation/lab/pipe1_off.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -7 -39 11 air
setblock -7 -43 11 air
setblock -7 -44 11 air
fill -7 -42 11 -7 -39 11 air
