#######
# Compiled from functions/puzzles/radiation/lab.mcscript
# to .//data/escapemap/functions/puzzles/radiation/lab/pipe1_on.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -7 -39 11 water
setblock -7 -43 11 barrier[waterlogged=true]
setblock -7 -44 11 water
