#######
# Compiled from functions/puzzles/radiation/lab.mcscript
# to .//data/escapemap/functions/puzzles/radiation/lab/pipe2_off.mcfunction
#
# Generated by Minecraft Script for 1.16
######
setblock -20 -43 3 air
setblock -20 -44 3 air
fill -20 -42 3 -20 -39 3 air
setblock -20 -39 3 slime_block