#######
# Compiled from escapemap/functions/laser/desert.mcscript
# to .//data/escapemap/functions/laser/desert/step_03_pitch/frame_015.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_laser,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.579313f,-0.170704f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.098017f,0.000000f,0.000000f,0.995185f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
data merge entity @e[type=minecraft:item_display,tag=desert,tag=laser_spout,limit=1] {start_interpolation:-1,interpolation_duration:3,transformation:{translation:[0.000000f,2.579313f,-0.170704f],scale:[1.000000f,1.000000f,1.000000f],left_rotation:[0.098017f,0.000000f,0.000000f,0.995185f],right_rotation:[0.000000f,0.000000f,0.000000f,1.000000f]}}
