#######
# Compiled from escapemap/functions/super_secrets/particles.mcscript
# to .//data/escapemap/functions/super_secrets/particles/head.mcfunction
#
# Generated by Minecraft Script for 1.16
######
particle minecraft:end_rod ~ ~ ~ 0.08 0.08 0.08 0.06 15 force
particle minecraft:electric_spark ~ ~ ~ 0.04 0.04 0.04 0.04 5 force
particle minecraft:dust{color:[0.35,0.85,1.0],scale:1.3} ~ ~ ~ 0.04 0.04 0.04 0.02 9 force
